# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/wifiprojection/message/WifiSecurityMode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/wifiprojection/message/WifiSecurityMode.proto\x12+aap_protobuf.service.wifiprojection.message*\xce\x01\n\x10WifiSecurityMode\x12\x19\n\x15UNKNOWN_SECURITY_MODE\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06WEP_64\x10\x02\x12\x0b\n\x07WEP_128\x10\x03\x12\x10\n\x0cWPA_PERSONAL\x10\x04\x12\x11\n\rWPA2_PERSONAL\x10\x05\x12\x15\n\x11WPA_WPA2_PERSONAL\x10\x06\x12\x12\n\x0eWPA_ENTERPRISE\x10\x07\x12\x13\n\x0fWPA2_ENTERPRISE\x10\x08\x12\x17\n\x13WPA_WPA2_ENTERPRISE\x10\tB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.wifiprojection.message.WifiSecurityMode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _WIFISECURITYMODE._serialized_start=116
  _WIFISECURITYMODE._serialized_end=322
# @@protoc_insertion_point(module_scope)
