# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/message/MediaSongNode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.mediabrowser.message import MediaSong_pb2 as aap__protobuf_dot_service_dot_mediabrowser_dot_message_dot_MediaSong__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/mediabrowser/message/MediaSongNode.proto\x12)aap_protobuf.service.mediabrowser.message\x1a\x39\x61\x61p_protobuf/service/mediabrowser/message/MediaSong.proto\"\x80\x01\n\rMediaSongNode\x12\x42\n\x04song\x18\x01 \x02(\x0b\x32\x34.aap_protobuf.service.mediabrowser.message.MediaSong\x12\x11\n\talbum_art\x18\x02 \x01(\x0c\x12\x18\n\x10\x64uration_seconds\x18\x03 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaSongNode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIASONGNODE._serialized_start=168
  _MEDIASONGNODE._serialized_end=296
# @@protoc_insertion_point(module_scope)
