# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/message/MediaSourceNode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.mediabrowser.message import MediaList_pb2 as aap__protobuf_dot_service_dot_mediabrowser_dot_message_dot_MediaList__pb2
from aasdk_proto.aap_protobuf.service.mediabrowser.message import MediaSource_pb2 as aap__protobuf_dot_service_dot_mediabrowser_dot_message_dot_MediaSource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/mediabrowser/message/MediaSourceNode.proto\x12)aap_protobuf.service.mediabrowser.message\x1a\x39\x61\x61p_protobuf/service/mediabrowser/message/MediaList.proto\x1a;aap_protobuf/service/mediabrowser/message/MediaSource.proto\"\xbc\x01\n\x0fMediaSourceNode\x12\x46\n\x06source\x18\x01 \x02(\x0b\x32\x36.aap_protobuf.service.mediabrowser.message.MediaSource\x12\r\n\x05start\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x43\n\x05lists\x18\x04 \x03(\x0b\x32\x34.aap_protobuf.service.mediabrowser.message.MediaList')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaSourceNode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIASOURCENODE._serialized_start=231
  _MEDIASOURCENODE._serialized_end=419
# @@protoc_insertion_point(module_scope)
