# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/message/MediaGetNode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/mediabrowser/message/MediaGetNode.proto\x12)aap_protobuf.service.mediabrowser.message\"H\n\x0cMediaGetNode\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x1b\n\rget_album_art\x18\x03 \x01(\x08:\x04true')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaGetNode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAGETNODE._serialized_start=107
  _MEDIAGETNODE._serialized_end=179
# @@protoc_insertion_point(module_scope)
