# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/video/message/VideoFocusNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.video.message import VideoFocusMode_pb2 as aap__protobuf_dot_service_dot_media_dot_video_dot_message_dot_VideoFocusMode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEaap_protobuf/service/media/video/message/VideoFocusNotification.proto\x12(aap_protobuf.service.media.video.message\x1a=aap_protobuf/service/media/video/message/VideoFocusMode.proto\"v\n\x16VideoFocusNotification\x12G\n\x05\x66ocus\x18\x01 \x01(\x0e\x32\x38.aap_protobuf.service.media.video.message.VideoFocusMode\x12\x13\n\x0bunsolicited\x18\x02 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.video.message.VideoFocusNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOFOCUSNOTIFICATION._serialized_start=178
  _VIDEOFOCUSNOTIFICATION._serialized_end=296
# @@protoc_insertion_point(module_scope)
