# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/video/message/VideoFocusReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/media/video/message/VideoFocusReason.proto\x12(aap_protobuf.service.media.video.message*H\n\x10VideoFocusReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10PHONE_SCREEN_OFF\x10\x01\x12\x11\n\rLAUNCH_NATIVE\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.video.message.VideoFocusReason_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOFOCUSREASON._serialized_start=109
  _VIDEOFOCUSREASON._serialized_end=181
# @@protoc_insertion_point(module_scope)
