# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/bluetooth/message/BluetoothAuthenticationResult.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import MessageStatus_pb2 as aap__protobuf_dot_shared_dot_MessageStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJaap_protobuf/service/bluetooth/message/BluetoothAuthenticationResult.proto\x12&aap_protobuf.service.bluetooth.message\x1a\'aap_protobuf/shared/MessageStatus.proto\"S\n\x1d\x42luetoothAuthenticationResult\x12\x32\n\x06status\x18\x01 \x02(\x0e\x32\".aap_protobuf.shared.MessageStatus')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.message.BluetoothAuthenticationResult_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLUETOOTHAUTHENTICATIONRESULT._serialized_start=159
  _BLUETOOTHAUTHENTICATIONRESULT._serialized_end=242
# @@protoc_insertion_point(module_scope)
