# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationDisplayInformationResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLaap_protobuf/channel/control/GalVerificationDisplayInformationResponse.proto\x12$aap_protobuf.service.control.message\"X\n)GalVerificationDisplayInformationResponse\x12\x14\n\x0cnative_width\x18\x01 \x02(\x05\x12\x15\n\rnative_height\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationDisplayInformationResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONDISPLAYINFORMATIONRESPONSE._serialized_start=118
  _GALVERIFICATIONDISPLAYINFORMATIONRESPONSE._serialized_end=206
# @@protoc_insertion_point(module_scope)
