# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationVideoFocus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.video.message import VideoFocusMode_pb2 as aap__protobuf_dot_service_dot_media_dot_video_dot_message_dot_VideoFocusMode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/channel/control/GalVerificationVideoFocus.proto\x12$aap_protobuf.service.control.message\x1a=aap_protobuf/service/media/video/message/VideoFocusMode.proto\"\x92\x01\n\x19GalVerificationVideoFocus\x12R\n\x10video_focus_mode\x18\x01 \x02(\x0e\x32\x38.aap_protobuf.service.media.video.message.VideoFocusMode\x12\x0c\n\x04\x64\x65ny\x18\x02 \x01(\x08\x12\x13\n\x0bunsolicited\x18\x03 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationVideoFocus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONVIDEOFOCUS._serialized_start=166
  _GALVERIFICATIONVIDEOFOCUS._serialized_end=312
# @@protoc_insertion_point(module_scope)
