# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationSetSensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.sensorsource.message import SensorBatch_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_SensorBatch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/channel/control/GalVerificationSetSensor.proto\x12$aap_protobuf.service.control.message\x1a;aap_protobuf/service/sensorsource/message/SensorBatch.proto\"c\n\x18GalVerificationSetSensor\x12G\n\x07sensors\x18\x01 \x01(\x0b\x32\x36.aap_protobuf.service.sensorsource.message.SensorBatch')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationSetSensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONSETSENSOR._serialized_start=162
  _GALVERIFICATIONSETSENSOR._serialized_end=261
# @@protoc_insertion_point(module_scope)
