# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationMediaSinkStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import Config_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_Config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/channel/control/GalVerificationMediaSinkStatus.proto\x12$aap_protobuf.service.control.message\x1a\x36\x61\x61p_protobuf/service/media/shared/message/Config.proto\"{\n\x1eGalVerificationMediaSinkStatus\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\x05\x12H\n\x06status\x18\x02 \x02(\x0e\x32\x38.aap_protobuf.service.media.shared.message.Config.Status')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationMediaSinkStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONMEDIASINKSTATUS._serialized_start=163
  _GALVERIFICATIONMEDIASINKSTATUS._serialized_end=286
# @@protoc_insertion_point(module_scope)
