# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationInjectInput.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.inputsource.message import InputReport_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_InputReport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/channel/control/GalVerificationInjectInput.proto\x12$aap_protobuf.service.control.message\x1a:aap_protobuf/service/inputsource/message/InputReport.proto\"b\n\x1aGalVerificationInjectInput\x12\x44\n\x05input\x18\x01 \x02(\x0b\x32\x35.aap_protobuf.service.inputsource.message.InputReport')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationInjectInput_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONINJECTINPUT._serialized_start=163
  _GALVERIFICATIONINJECTINPUT._serialized_end=261
# @@protoc_insertion_point(module_scope)
