# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediaplayback/message/MediaPlaybackMetadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/service/mediaplayback/message/MediaPlaybackMetadata.proto\x12*aap_protobuf.service.mediaplayback.message\"\x93\x01\n\x15MediaPlaybackMetadata\x12\x0c\n\x04song\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\x12\x11\n\talbum_art\x18\x04 \x01(\x0c\x12\x10\n\x08playlist\x18\x05 \x01(\t\x12\x18\n\x10\x64uration_seconds\x18\x06 \x01(\r\x12\x0e\n\x06rating\x18\x07 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediaplayback.message.MediaPlaybackMetadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAPLAYBACKMETADATA._serialized_start=119
  _MEDIAPLAYBACKMETADATA._serialized_end=266
# @@protoc_insertion_point(module_scope)
