# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediaplayback/message/MediaPlaybackStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDaap_protobuf/service/mediaplayback/message/MediaPlaybackStatus.proto\x12*aap_protobuf.service.mediaplayback.message\"\xff\x01\n\x13MediaPlaybackStatus\x12T\n\x05state\x18\x01 \x01(\x0e\x32\x45.aap_protobuf.service.mediaplayback.message.MediaPlaybackStatus.State\x12\x14\n\x0cmedia_source\x18\x02 \x01(\t\x12\x18\n\x10playback_seconds\x18\x03 \x01(\r\x12\x0f\n\x07shuffle\x18\x04 \x01(\x08\x12\x0e\n\x06repeat\x18\x05 \x01(\x08\x12\x12\n\nrepeat_one\x18\x06 \x01(\x08\"-\n\x05State\x12\x0b\n\x07STOPPED\x10\x01\x12\x0b\n\x07PLAYING\x10\x02\x12\n\n\x06PAUSED\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediaplayback.message.MediaPlaybackStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAPLAYBACKSTATUS._serialized_start=117
  _MEDIAPLAYBACKSTATUS._serialized_end=372
  _MEDIAPLAYBACKSTATUS_STATE._serialized_start=327
  _MEDIAPLAYBACKSTATUS_STATE._serialized_end=372
# @@protoc_insertion_point(module_scope)
