# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/genericnotification/message/GenericNotificationSubscribe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSaap_protobuf/service/genericnotification/message/GenericNotificationSubscribe.proto\x12\x30\x61\x61p_protobuf.service.genericnotification.message\"\x1e\n\x1cGenericNotificationSubscribe')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.genericnotification.message.GenericNotificationSubscribe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICNOTIFICATIONSUBSCRIBE._serialized_start=137
  _GENERICNOTIFICATIONSUBSCRIBE._serialized_end=167
# @@protoc_insertion_point(module_scope)
