# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/GetTrafficUpdateRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@aap_protobuf/service/radio/message/GetTrafficUpdateRequest.proto\x12\"aap_protobuf.service.radio.message\"+\n\x17GetTrafficUpdateRequest\x12\x10\n\x08radio_id\x18\x01 \x02(\x05\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.GetTrafficUpdateRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _GETTRAFFICUPDATEREQUEST._serialized_start=104
  _GETTRAFFICUPDATEREQUEST._serialized_end=147
# @@protoc_insertion_point(module_scope)
