# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/HdAcquisionState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/radio/message/HdAcquisionState.proto\x12\"aap_protobuf.service.radio.message*A\n\x10HdAcquisionState\x12\n\n\x06\x41NALOG\x10\x00\x12\x10\n\x0c\x41\x43QUIRING_HD\x10\x01\x12\x0f\n\x0b\x41\x43QUIRED_HD\x10\x02\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdAcquisionState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _HDACQUISIONSTATE._serialized_start=97
  _HDACQUISIONSTATE._serialized_end=162
# @@protoc_insertion_point(module_scope)
