# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/HdRadioStationInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import HdRadioSisData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioSisData__pb2
from aasdk_proto.aap_protobuf.service.radio.message import HdRadioPsdData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioPsdData__pb2
from aasdk_proto.aap_protobuf.service.radio.message import HdAcquisionState_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdAcquisionState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/radio/message/HdRadioStationInfo.proto\x12\"aap_protobuf.service.radio.message\x1a\x37\x61\x61p_protobuf/service/radio/message/HdRadioSisData.proto\x1a\x37\x61\x61p_protobuf/service/radio/message/HdRadioPsdData.proto\x1a\x39\x61\x61p_protobuf/service/radio/message/HdAcquisionState.proto\"\x88\x02\n\x12HdRadioStationInfo\x12O\n\x11\x61\x63quisition_state\x18\x01 \x01(\x0e\x32\x34.aap_protobuf.service.radio.message.HdAcquisionState\x12\x1f\n\x17\x64igital_signal_strength\x18\x02 \x01(\x05\x12?\n\x03psd\x18\x03 \x01(\x0b\x32\x32.aap_protobuf.service.radio.message.HdRadioPsdData\x12?\n\x03sis\x18\x04 \x01(\x0b\x32\x32.aap_protobuf.service.radio.message.HdRadioSisDataB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdRadioStationInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _HDRADIOSTATIONINFO._serialized_start=273
  _HDRADIOSTATIONINFO._serialized_end=537
# @@protoc_insertion_point(module_scope)
