# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/HdRadioCommercial.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/radio/message/HdRadioCommercial.proto\x12\"aap_protobuf.service.radio.message\"\x87\x01\n\x11HdRadioCommercial\x12\x10\n\x08\x65ncoding\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\t\x12\r\n\x05valid\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x10\n\x08received\x18\x05 \x01(\x05\x12\x0e\n\x06seller\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\tB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdRadioCommercial_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _HDRADIOCOMMERCIAL._serialized_start=99
  _HDRADIOCOMMERCIAL._serialized_end=234
# @@protoc_insertion_point(module_scope)
