# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/HdRadioPsdData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import HdRadioComment_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioComment__pb2
from aasdk_proto.aap_protobuf.service.radio.message import HdRadioCommercial_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioCommercial__pb2
from aasdk_proto.aap_protobuf.service.radio.message import HdRadioArtistExperience_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_HdRadioArtistExperience__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/radio/message/HdRadioPsdData.proto\x12\"aap_protobuf.service.radio.message\x1a\x37\x61\x61p_protobuf/service/radio/message/HdRadioComment.proto\x1a:aap_protobuf/service/radio/message/HdRadioCommercial.proto\x1a@aap_protobuf/service/radio/message/HdRadioArtistExperience.proto\"\xb5\x02\n\x0eHdRadioPsdData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x43\n\x07\x63omment\x18\x05 \x01(\x0b\x32\x32.aap_protobuf.service.radio.message.HdRadioComment\x12I\n\ncommercial\x18\x06 \x01(\x0b\x32\x35.aap_protobuf.service.radio.message.HdRadioCommercial\x12V\n\x11\x61rtist_experience\x18\x07 \x01(\x0b\x32;.aap_protobuf.service.radio.message.HdRadioArtistExperienceB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdRadioPsdData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _HDRADIOPSDDATA._serialized_start=279
  _HDRADIOPSDDATA._serialized_end=588
# @@protoc_insertion_point(module_scope)
