# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/MuteRadioRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/radio/message/MuteRadioRequest.proto\x12\"aap_protobuf.service.radio.message\"2\n\x10MuteRadioRequest\x12\x10\n\x08radio_id\x18\x01 \x01(\x05\x12\x0c\n\x04mute\x18\x02 \x02(\x08\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.MuteRadioRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _MUTERADIOREQUEST._serialized_start=97
  _MUTERADIOREQUEST._serialized_end=147
# @@protoc_insertion_point(module_scope)
