# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RadioProperties.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import RadioType_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioType__pb2
from aasdk_proto.aap_protobuf.service.radio.message import Range_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_Range__pb2
from aasdk_proto.aap_protobuf.service.radio.message import RdsType_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RdsType__pb2
from aasdk_proto.aap_protobuf.service.radio.message import TrafficServiceType_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_TrafficServiceType__pb2
from aasdk_proto.aap_protobuf.service.radio.message import ItuRegion_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_ItuRegion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/radio/message/RadioProperties.proto\x12\"aap_protobuf.service.radio.message\x1a\x32\x61\x61p_protobuf/service/radio/message/RadioType.proto\x1a.aap_protobuf/service/radio/message/Range.proto\x1a\x30\x61\x61p_protobuf/service/radio/message/RdsType.proto\x1a;aap_protobuf/service/radio/message/TrafficServiceType.proto\x1a\x32\x61\x61p_protobuf/service/radio/message/ItuRegion.proto\"\xa1\x04\n\x0fRadioProperties\x12\x10\n\x08radio_id\x18\x01 \x02(\x05\x12;\n\x04type\x18\x02 \x02(\x0e\x32-.aap_protobuf.service.radio.message.RadioType\x12@\n\rchannel_range\x18\x03 \x03(\x0b\x32).aap_protobuf.service.radio.message.Range\x12\x18\n\x10\x63hannel_spacings\x18\x04 \x03(\x05\x12\x17\n\x0f\x63hannel_spacing\x18\x05 \x02(\x05\x12\x18\n\x10\x62\x61\x63kground_tuner\x18\x06 \x01(\x08\x12\x35\n\x06region\x18\x07 \x01(\x0e\x32%.aap_protobuf.service.radio.ItuRegion\x12\x38\n\x03rds\x18\x08 \x01(\x0e\x32+.aap_protobuf.service.radio.message.RdsType\x12\x11\n\taf_switch\x18\t \x01(\x08\x12\n\n\x02ta\x18\n \x01(\x08\x12O\n\x0ftraffic_service\x18\x0b \x01(\x0e\x32\x36.aap_protobuf.service.radio.message.TrafficServiceType\x12\x16\n\x0e\x61udio_loopback\x18\x0c \x01(\x08\x12\x17\n\x0fmute_capability\x18\r \x01(\x08\x12\x1e\n\x16station_presets_access\x18\x0e \x01(\x05\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioProperties_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOPROPERTIES._serialized_start=360
  _RADIOPROPERTIES._serialized_end=905
# @@protoc_insertion_point(module_scope)
