# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RadioStateNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import RadioStationInfo_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioStationInfo__pb2
from aasdk_proto.aap_protobuf.service.radio.message import StationPresetList_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_StationPresetList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/radio/message/RadioStateNotification.proto\x12\"aap_protobuf.service.radio.message\x1a\x39\x61\x61p_protobuf/service/radio/message/RadioStationInfo.proto\x1a:aap_protobuf/service/radio/message/StationPresetList.proto\"\xd1\x02\n\x16RadioStateNotification\x12\x1c\n\x14radio_source_enabled\x18\x01 \x02(\x08\x12\x13\n\x0bradio_muted\x18\x02 \x01(\x08\x12\x17\n\x0f\x61\x63tive_radio_id\x18\x03 \x02(\x05\x12J\n\x0cstation_info\x18\x04 \x02(\x0b\x32\x34.aap_protobuf.service.radio.message.RadioStationInfo\x12J\n\x0cprogram_list\x18\x05 \x03(\x0b\x32\x34.aap_protobuf.service.radio.message.RadioStationInfo\x12S\n\x14station_preset_lists\x18\x06 \x03(\x0b\x32\x35.aap_protobuf.service.radio.message.StationPresetListB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioStateNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOSTATENOTIFICATION._serialized_start=223
  _RADIOSTATENOTIFICATION._serialized_end=560
# @@protoc_insertion_point(module_scope)
