# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RadioStationInfoNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import RadioStationInfo_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioStationInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEaap_protobuf/service/radio/message/RadioStationInfoNotification.proto\x12\"aap_protobuf.service.radio.message\x1a\x39\x61\x61p_protobuf/service/radio/message/RadioStationInfo.proto\"|\n\x1cRadioStationInfoNotification\x12\x10\n\x08radio_id\x18\x01 \x02(\x05\x12J\n\x0cstation_info\x18\x02 \x02(\x0b\x32\x34.aap_protobuf.service.radio.message.RadioStationInfoB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioStationInfoNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOSTATIONINFONOTIFICATION._serialized_start=168
  _RADIOSTATIONINFONOTIFICATION._serialized_end=292
# @@protoc_insertion_point(module_scope)
