# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RadioStationInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import RadioType_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioType__pb2
from aasdk_proto.aap_protobuf.service.radio.message import RadioStationMetaData_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioStationMetaData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/radio/message/RadioStationInfo.proto\x12\"aap_protobuf.service.radio.message\x1a\x32\x61\x61p_protobuf/service/radio/message/RadioType.proto\x1a=aap_protobuf/service/radio/message/RadioStationMetaData.proto\"\xc2\x01\n\x10RadioStationInfo\x12;\n\x04type\x18\x01 \x02(\x0e\x32-.aap_protobuf.service.radio.message.RadioType\x12\x0f\n\x07\x63hannel\x18\x02 \x02(\x05\x12\x13\n\x0bsub_channel\x18\x03 \x01(\x05\x12K\n\tmeta_data\x18\x04 \x01(\x0b\x32\x38.aap_protobuf.service.radio.message.RadioStationMetaDataB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioStationInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOSTATIONINFO._serialized_start=213
  _RADIOSTATIONINFO._serialized_end=407
# @@protoc_insertion_point(module_scope)
