# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RadioType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2aap_protobuf/service/radio/message/RadioType.proto\x12\"aap_protobuf.service.radio.message*f\n\tRadioType\x12\x0c\n\x08\x41M_RADIO\x10\x00\x12\x0c\n\x08\x46M_RADIO\x10\x01\x12\x0f\n\x0b\x41M_HD_RADIO\x10\x02\x12\x0f\n\x0b\x46M_HD_RADIO\x10\x03\x12\r\n\tDAB_RADIO\x10\x04\x12\x0c\n\x08XM_RADIO\x10\x05\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RadioType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOTYPE._serialized_start=90
  _RADIOTYPE._serialized_end=192
# @@protoc_insertion_point(module_scope)
