# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/RdsData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0aap_protobuf/service/radio/message/RdsData.proto\x12\"aap_protobuf.service.radio.message\"\xff\x01\n\x07RdsData\x12\x1f\n\x17\x61lternative_frequencies\x18\x01 \x03(\x05\x12\x12\n\nprogram_id\x18\x02 \x01(\x05\x12\x1b\n\x13music_speech_switch\x18\x03 \x01(\x05\x12\x1c\n\x14program_service_name\x18\x04 \x01(\t\x12\x14\n\x0cprogram_type\x18\x05 \x01(\x05\x12\x19\n\x11program_type_name\x18\x06 \x01(\t\x12\x12\n\nradio_text\x18\x07 \x01(\t\x12\x1c\n\x14traffic_program_flag\x18\x08 \x01(\x08\x12!\n\x19traffic_announcement_flag\x18\t \x01(\x08\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.RdsData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RDSDATA._serialized_start=89
  _RDSDATA._serialized_end=344
# @@protoc_insertion_point(module_scope)
