# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/StationPresetsNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import StationPresetList_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_StationPresetList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/radio/message/StationPresetsNotification.proto\x12\"aap_protobuf.service.radio.message\x1a:aap_protobuf/service/radio/message/StationPresetList.proto\"i\n\x1aStationPresetsNotification\x12K\n\x0cpreset_lists\x18\x02 \x03(\x0b\x32\x35.aap_protobuf.service.radio.message.StationPresetListB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.StationPresetsNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _STATIONPRESETSNOTIFICATION._serialized_start=167
  _STATIONPRESETSNOTIFICATION._serialized_end=272
# @@protoc_insertion_point(module_scope)
