# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/TrafficIncident.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import Location_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_Location__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/radio/message/TrafficIncident.proto\x12\"aap_protobuf.service.radio.message\x1a\x31\x61\x61p_protobuf/service/radio/message/Location.proto\"\x89\x01\n\x0fTrafficIncident\x12\x12\n\nevent_code\x18\x01 \x02(\x05\x12>\n\x08location\x18\x02 \x02(\x0b\x32,.aap_protobuf.service.radio.message.Location\x12\"\n\x1a\x65xpected_incident_duration\x18\x03 \x02(\x05\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.TrafficIncident_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _TRAFFICINCIDENT._serialized_start=148
  _TRAFFICINCIDENT._serialized_end=285
# @@protoc_insertion_point(module_scope)
