# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WifiInfoResponseMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dWifiInfoResponseMessage.proto\x12\x14\x61\x61sdk.proto.messages\"\xea\x04\n\x10WifiInfoResponse\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12=\n\x06status\x18\x03 \x02(\x0e\x32-.aasdk.proto.messages.WifiInfoResponse.Status\"\xf4\x03\n\x06Status\x12\x1e\n\x1aSTATUS_UNSOLICITED_MESSAGE\x10\x01\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12)\n\x1cSTATUS_NO_COMPATIBLE_VERSION\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12-\n STATUS_WIFI_INACCESSIBLE_CHANNEL\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_WIFI_INCORRECT_CREDENTIALS\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_PROJECTION_ALREADY_STARTED\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n\x14STATUS_WIFI_DISABLED\x10\xfb\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12(\n\x1bSTATUS_WIFI_NOT_YET_STARTED\x10\xfa\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n\x13STATUS_INVALID_HOST\x10\xf9\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_NO_SUPPORTED_WIFI_CHANNELS\x10\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x34\n\'STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE\x10\xf7\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\'\n\x1aSTATUS_PHONE_WIFI_DISABLED\x10\xf6\xff\xff\xff\xff\xff\xff\xff\xff\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WifiInfoResponseMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIINFORESPONSE._serialized_start=56
  _WIFIINFORESPONSE._serialized_end=674
  _WIFIINFORESPONSE_STATUS._serialized_start=174
  _WIFIINFORESPONSE_STATUS._serialized_end=674
# @@protoc_insertion_point(module_scope)
