# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WifiChannelMessageIdsEnum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fWifiChannelMessageIdsEnum.proto\x12\x0f\x61\x61sdk.proto.ids\"]\n\x12WifiChannelMessage\"G\n\x04\x45num\x12\x08\n\x04NONE\x10\x00\x12\x19\n\x13\x43REDENTIALS_REQUEST\x10\x81\x80\x02\x12\x1a\n\x14\x43REDENTIALS_RESPONSE\x10\x82\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WifiChannelMessageIdsEnum_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFICHANNELMESSAGE._serialized_start=52
  _WIFICHANNELMESSAGE._serialized_end=145
  _WIFICHANNELMESSAGE_ENUM._serialized_start=74
  _WIFICHANNELMESSAGE_ENUM._serialized_end=145
# @@protoc_insertion_point(module_scope)
