# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/RadioService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import RadioProperties_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_RadioProperties__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-aap_protobuf/service/radio/RadioService.proto\x12\x1a\x61\x61p_protobuf.service.radio\x1a\x38\x61\x61p_protobuf/service/radio/message/RadioProperties.proto\"]\n\x0cRadioService\x12M\n\x10radio_properties\x18\x01 \x03(\x0b\x32\x33.aap_protobuf.service.radio.message.RadioPropertiesB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.RadioService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOSERVICE._serialized_start=135
  _RADIOSERVICE._serialized_end=228
# @@protoc_insertion_point(module_scope)
