# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/RadioMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/aap_protobuf/service/radio/RadioMessageId.proto\x12\x1a\x61\x61p_protobuf.service.radio*\x8d\t\n\x0eRadioMessageId\x12-\n\'RADIO_MESSAGE_ACTIVE_RADIO_NOTIFICATION\x10\x81\x80\x02\x12/\n)RADIO_MESSAGE_SELECT_ACTIVE_RADIO_REQUEST\x10\x82\x80\x02\x12(\n\"RADIO_MESSAGE_STEP_CHANNEL_REQUEST\x10\x83\x80\x02\x12)\n#RADIO_MESSAGE_STEP_CHANNEL_RESPONSE\x10\x84\x80\x02\x12(\n\"RADIO_MESSAGE_SEEK_STATION_REQUEST\x10\x85\x80\x02\x12)\n#RADIO_MESSAGE_SEEK_STATION_RESPONSE\x10\x86\x80\x02\x12)\n#RADIO_MESSAGE_SCAN_STATIONS_REQUEST\x10\x87\x80\x02\x12*\n$RADIO_MESSAGE_SCAN_STATIONS_RESPONSE\x10\x88\x80\x02\x12+\n%RADIO_MESSAGE_TUNE_TO_STATION_REQUEST\x10\x89\x80\x02\x12,\n&RADIO_MESSAGE_TUNE_TO_STATION_RESPONSE\x10\x8a\x80\x02\x12,\n&RADIO_MESSAGE_GET_PROGRAM_LIST_REQUEST\x10\x8b\x80\x02\x12-\n\'RADIO_MESSAGE_GET_PROGRAM_LIST_RESPONSE\x10\x8c\x80\x02\x12\x30\n*RADIO_MESSAGE_STATION_PRESETS_NOTIFICATION\x10\x8d\x80\x02\x12-\n\'RADIO_MESSAGE_CANCEL_OPERATIONS_REQUEST\x10\x8e\x80\x02\x12.\n(RADIO_MESSAGE_CANCEL_OPERATIONS_RESPONSE\x10\x8f\x80\x02\x12\x35\n/RADIO_MESSAGE_CONFIGURE_CHANNEL_SPACING_REQUEST\x10\x90\x80\x02\x12\x36\n0RADIO_MESSAGE_CONFIGURE_CHANNEL_SPACING_RESPONSE\x10\x91\x80\x02\x12\x33\n-RADIO_MESSAGE_RADIO_STATION_INFO_NOTIFICATION\x10\x92\x80\x02\x12&\n RADIO_MESSAGE_MUTE_RADIO_REQUEST\x10\x93\x80\x02\x12\'\n!RADIO_MESSAGE_MUTE_RADIO_RESPONSE\x10\x94\x80\x02\x12.\n(RADIO_MESSAGE_GET_TRAFFIC_UPDATE_REQUEST\x10\x95\x80\x02\x12/\n)RADIO_MESSAGE_GET_TRAFFIC_UPDATE_RESPONSE\x10\x96\x80\x02\x12(\n\"RADIO_MESSAGE_RADIO_SOURCE_REQUEST\x10\x97\x80\x02\x12)\n#RADIO_MESSAGE_RADIO_SOURCE_RESPONSE\x10\x98\x80\x02\x12&\n RADIO_MESSAGE_STATE_NOTIFICATION\x10\x99\x80\x02\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.RadioMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _RADIOMESSAGEID._serialized_start=80
  _RADIOMESSAGEID._serialized_end=1245
# @@protoc_insertion_point(module_scope)
