# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/wifiprojection/message/AccessPointType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/wifiprojection/message/AccessPointType.proto\x12+aap_protobuf.service.wifiprojection.message**\n\x0f\x41\x63\x63\x65ssPointType\x12\n\n\x06STATIC\x10\x00\x12\x0b\n\x07\x44YNAMIC\x10\x01\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.wifiprojection.message.AccessPointType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _ACCESSPOINTTYPE._serialized_start=114
  _ACCESSPOINTTYPE._serialized_end=156
# @@protoc_insertion_point(module_scope)
