# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/wifiprojection/message/WifiCredentialsResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.wifiprojection.message import AccessPointType_pb2 as aap__protobuf_dot_service_dot_wifiprojection_dot_message_dot_AccessPointType__pb2
from aasdk_proto.aap_protobuf.service.wifiprojection.message import WifiSecurityMode_pb2 as aap__protobuf_dot_service_dot_wifiprojection_dot_message_dot_WifiSecurityMode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIaap_protobuf/service/wifiprojection/message/WifiCredentialsResponse.proto\x12+aap_protobuf.service.wifiprojection.message\x1a\x41\x61\x61p_protobuf/service/wifiprojection/message/AccessPointType.proto\x1a\x42\x61\x61p_protobuf/service/wifiprojection/message/WifiSecurityMode.proto\"\xa4\x02\n\x17WifiCredentialsResponse\x12\x19\n\x11\x63\x61r_wifi_password\x18\x01 \x01(\t\x12]\n\x16\x63\x61r_wifi_security_mode\x18\x02 \x01(\x0e\x32=.aap_protobuf.service.wifiprojection.message.WifiSecurityMode\x12\x15\n\rcar_wifi_ssid\x18\x03 \x01(\t\x12\x1f\n\x17supported_wifi_channels\x18\x04 \x03(\x05\x12W\n\x11\x61\x63\x63\x65ss_point_type\x18\x05 \x01(\x0e\x32<.aap_protobuf.service.wifiprojection.message.AccessPointTypeB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.wifiprojection.message.WifiCredentialsResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _WIFICREDENTIALSRESPONSE._serialized_start=258
  _WIFICREDENTIALSRESPONSE._serialized_end=550
# @@protoc_insertion_point(module_scope)
