# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/SensorMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/sensorsource/SensorMessageId.proto\x12!aap_protobuf.service.sensorsource*\x86\x01\n\x0fSensorMessageId\x12\x1c\n\x16SENSOR_MESSAGE_REQUEST\x10\x81\x80\x02\x12\x1d\n\x17SENSOR_MESSAGE_RESPONSE\x10\x82\x80\x02\x12\x1a\n\x14SENSOR_MESSAGE_BATCH\x10\x83\x80\x02\x12\x1a\n\x14SENSOR_MESSAGE_ERROR\x10\x84\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.SensorMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORMESSAGEID._serialized_start=95
  _SENSORMESSAGEID._serialized_end=229
# @@protoc_insertion_point(module_scope)
