# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/genericnotification/GenericNotificationMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKaap_protobuf/service/genericnotification/GenericNotificationMessageId.proto\x12(aap_protobuf.service.genericnotification*\xb0\x01\n\x1cGenericNotificationMessageId\x12$\n\x1eGENERIC_NOTIFICATION_SUBSCRIBE\x10\x81\x80\x02\x12&\n GENERIC_NOTIFICATION_UNSUBSCRIBE\x10\x82\x80\x02\x12\"\n\x1cGENERIC_NOTIFICATION_MESSAGE\x10\x83\x80\x02\x12\x1e\n\x18GENERIC_NOTIFICATION_ACK\x10\x84\x80\x02\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.genericnotification.GenericNotificationMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _GENERICNOTIFICATIONMESSAGEID._serialized_start=122
  _GENERICNOTIFICATIONMESSAGEID._serialized_end=298
# @@protoc_insertion_point(module_scope)
