# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationScreenCaptureResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGaap_protobuf/channel/control/GalVerificationScreenCaptureResponse.proto\x12$aap_protobuf.service.control.message\">\n$GalVerificationScreenCaptureResponse\x12\x16\n\x0escreen_capture\x18\x01 \x02(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationScreenCaptureResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONSCREENCAPTURERESPONSE._serialized_start=113
  _GALVERIFICATIONSCREENCAPTURERESPONSE._serialized_end=175
# @@protoc_insertion_point(module_scope)
