# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GalVerificationScreenCaptureRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/channel/control/GalVerificationScreenCaptureRequest.proto\x12$aap_protobuf.service.control.message\"%\n#GalVerificationScreenCaptureRequest')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GalVerificationScreenCaptureRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GALVERIFICATIONSCREENCAPTUREREQUEST._serialized_start=112
  _GALVERIFICATIONSCREENCAPTUREREQUEST._serialized_end=149
# @@protoc_insertion_point(module_scope)
