# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/GoogleDiagnosticsVendorExtensionMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLaap_protobuf/channel/control/GoogleDiagnosticsVendorExtensionMessageId.proto\x12$aap_protobuf.service.control.message*t\n)GoogleDiagnosticsVendorExtensionMessageId\x12\"\n\x1e\x44IAGNOSTICS_BUG_REPORT_REQUEST\x10\x01\x12#\n\x1f\x44IAGNOSTICS_BUG_REPORT_RESPONSE\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.GoogleDiagnosticsVendorExtensionMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOOGLEDIAGNOSTICSVENDOREXTENSIONMESSAGEID._serialized_start=118
  _GOOGLEDIAGNOSTICSVENDOREXTENSIONMESSAGEID._serialized_end=234
# @@protoc_insertion_point(module_scope)
