# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/channel/control/SessionConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/channel/control/SessionConfiguration.proto\x12\x13\x61\x61p_protobuf.shared*\x98\x01\n\x14SessionConfiguration\x12\x18\n\x14UI_CONFIG_HIDE_CLOCK\x10\x01\x12\x1f\n\x1bUI_CONFIG_HIDE_PHONE_SIGNAL\x10\x02\x12 \n\x1cUI_CONFIG_HIDE_BATTERY_LEVEL\x10\x04\x12#\n\x1f\x43\x41N_PLAY_NATIVE_MEDIA_DURING_VR\x10\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.channel.control.SessionConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONCONFIGURATION._serialized_start=81
  _SESSIONCONFIGURATION._serialized_end=233
# @@protoc_insertion_point(module_scope)
