# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/bluetooth/BluetoothMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/bluetooth/BluetoothMessageId.proto\x12\x1e\x61\x61p_protobuf.service.bluetooth*\xc3\x01\n\x12\x42luetoothMessageId\x12\'\n!BLUETOOTH_MESSAGE_PAIRING_REQUEST\x10\x81\x80\x02\x12(\n\"BLUETOOTH_MESSAGE_PAIRING_RESPONSE\x10\x82\x80\x02\x12+\n%BLUETOOTH_MESSAGE_AUTHENTICATION_DATA\x10\x83\x80\x02\x12-\n\'BLUETOOTH_MESSAGE_AUTHENTICATION_RESULT\x10\x84\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.BluetoothMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLUETOOTHMESSAGEID._serialized_start=92
  _BLUETOOTHMESSAGEID._serialized_end=287
# @@protoc_insertion_point(module_scope)
