# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/bluetooth/BluetoothService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.bluetooth.message import BluetoothPairingMethod_pb2 as aap__protobuf_dot_service_dot_bluetooth_dot_message_dot_BluetoothPairingMethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aap_protobuf/service/bluetooth/BluetoothService.proto\x12\x1e\x61\x61p_protobuf.service.bluetooth\x1a\x43\x61\x61p_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto\"\x8e\x01\n\x10\x42luetoothService\x12\x13\n\x0b\x63\x61r_address\x18\x01 \x02(\t\x12\x65\n\x19supported_pairing_methods\x18\x02 \x03(\x0e\x32>.aap_protobuf.service.bluetooth.message.BluetoothPairingMethodB\x02\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.BluetoothService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLUETOOTHSERVICE.fields_by_name['supported_pairing_methods']._options = None
  _BLUETOOTHSERVICE.fields_by_name['supported_pairing_methods']._serialized_options = b'\020\001'
  _BLUETOOTHSERVICE._serialized_start=159
  _BLUETOOTHSERVICE._serialized_end=301
# @@protoc_insertion_point(module_scope)
