# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDaap_protobuf/service/navigationstatus/message/NavigationStatus.proto\x12-aap_protobuf.service.navigationstatus.message\"\xca\x01\n\x10NavigationStatus\x12\x64\n\x06status\x18\x01 \x02(\x0e\x32T.aap_protobuf.service.navigationstatus.message.NavigationStatus.NavigationStatusEnum\"P\n\x14NavigationStatusEnum\x12\x0f\n\x0bUNAVAILABLE\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x12\r\n\tREROUTING\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTATUS._serialized_start=120
  _NAVIGATIONSTATUS._serialized_end=322
  _NAVIGATIONSTATUS_NAVIGATIONSTATUSENUM._serialized_start=242
  _NAVIGATIONSTATUS_NAVIGATIONSTATUSENUM._serialized_end=322
# @@protoc_insertion_point(module_scope)
