# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationCurrentPosition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationStepDistance_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationStepDistance__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationDestinationDistance_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationDestinationDistance__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationRoad_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationRoad__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMaap_protobuf/service/navigationstatus/message/NavigationCurrentPosition.proto\x12-aap_protobuf.service.navigationstatus.message\x1aJaap_protobuf/service/navigationstatus/message/NavigationStepDistance.proto\x1aQaap_protobuf/service/navigationstatus/message/NavigationDestinationDistance.proto\x1a\x42\x61\x61p_protobuf/service/navigationstatus/message/NavigationRoad.proto\"\xbb\x02\n\x19NavigationCurrentPosition\x12\\\n\rstep_distance\x18\x01 \x01(\x0b\x32\x45.aap_protobuf.service.navigationstatus.message.NavigationStepDistance\x12k\n\x15\x64\x65stination_distances\x18\x02 \x03(\x0b\x32L.aap_protobuf.service.navigationstatus.message.NavigationDestinationDistance\x12S\n\x0c\x63urrent_road\x18\x03 \x01(\x0b\x32=.aap_protobuf.service.navigationstatus.message.NavigationRoad')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationCurrentPosition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONCURRENTPOSITION._serialized_start=356
  _NAVIGATIONCURRENTPOSITION._serialized_end=671
# @@protoc_insertion_point(module_scope)
