# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationDistance.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/service/navigationstatus/message/NavigationDistance.proto\x12-aap_protobuf.service.navigationstatus.message\"\xad\x02\n\x12NavigationDistance\x12\x0e\n\x06meters\x18\x01 \x01(\x05\x12\x15\n\rdisplay_value\x18\x02 \x01(\t\x12\x66\n\rdisplay_units\x18\x03 \x01(\x0e\x32O.aap_protobuf.service.navigationstatus.message.NavigationDistance.DistanceUnits\"\x87\x01\n\rDistanceUnits\x12\x19\n\x15UNKNOWN_DISTANCE_UNIT\x10\x00\x12\n\n\x06METERS\x10\x01\x12\x0e\n\nKILOMETERS\x10\x02\x12\x11\n\rKILOMETERS_P1\x10\x03\x12\t\n\x05MILES\x10\x04\x12\x0c\n\x08MILES_P1\x10\x05\x12\x08\n\x04\x46\x45\x45T\x10\x06\x12\t\n\x05YARDS\x10\x07')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationDistance_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONDISTANCE._serialized_start=122
  _NAVIGATIONDISTANCE._serialized_end=423
  _NAVIGATIONDISTANCE_DISTANCEUNITS._serialized_start=288
  _NAVIGATIONDISTANCE_DISTANCEUNITS._serialized_end=423
# @@protoc_insertion_point(module_scope)
