# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationDestinationDistance.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationDistance_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationDistance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQaap_protobuf/service/navigationstatus/message/NavigationDestinationDistance.proto\x12-aap_protobuf.service.navigationstatus.message\x1a\x46\x61\x61p_protobuf/service/navigationstatus/message/NavigationDistance.proto\"\xb8\x01\n\x1dNavigationDestinationDistance\x12S\n\x08\x64istance\x18\x01 \x01(\x0b\x32\x41.aap_protobuf.service.navigationstatus.message.NavigationDistance\x12!\n\x19\x65stimated_time_at_arrival\x18\x02 \x01(\t\x12\x1f\n\x17time_to_arrival_seconds\x18\x03 \x01(\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationDestinationDistance_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONDESTINATIONDISTANCE._serialized_start=205
  _NAVIGATIONDESTINATIONDISTANCE._serialized_end=389
# @@protoc_insertion_point(module_scope)
