# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationLane.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/navigationstatus/message/NavigationLane.proto\x12-aap_protobuf.service.navigationstatus.message\"\xb1\x03\n\x0eNavigationLane\x12\x64\n\x0flane_directions\x18\x01 \x03(\x0b\x32K.aap_protobuf.service.navigationstatus.message.NavigationLane.LaneDirection\x1a\xb8\x02\n\rLaneDirection\x12`\n\x05shape\x18\x01 \x01(\x0e\x32Q.aap_protobuf.service.navigationstatus.message.NavigationLane.LaneDirection.Shape\x12\x16\n\x0eis_highlighted\x18\x02 \x01(\x08\"\xac\x01\n\x05Shape\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08STRAIGHT\x10\x01\x12\x0f\n\x0bSLIGHT_LEFT\x10\x02\x12\x10\n\x0cSLIGHT_RIGHT\x10\x03\x12\x0f\n\x0bNORMAL_LEFT\x10\x04\x12\x10\n\x0cNORMAL_RIGHT\x10\x05\x12\x0e\n\nSHARP_LEFT\x10\x06\x12\x0f\n\x0bSHARP_RIGHT\x10\x07\x12\x0f\n\x0bU_TURN_LEFT\x10\x08\x12\x10\n\x0cU_TURN_RIGHT\x10\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationLane_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONLANE._serialized_start=118
  _NAVIGATIONLANE._serialized_end=551
  _NAVIGATIONLANE_LANEDIRECTION._serialized_start=239
  _NAVIGATIONLANE_LANEDIRECTION._serialized_end=551
  _NAVIGATIONLANE_LANEDIRECTION_SHAPE._serialized_start=379
  _NAVIGATIONLANE_LANEDIRECTION_SHAPE._serialized_end=551
# @@protoc_insertion_point(module_scope)
