# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/genericnotification/message/GenericNotificationMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQaap_protobuf/service/genericnotification/message/GenericNotificationMessage.proto\x12\x30\x61\x61p_protobuf.service.genericnotification.message\"D\n\x1aGenericNotificationMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04icon\x18\x03 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.genericnotification.message.GenericNotificationMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICNOTIFICATIONMESSAGE._serialized_start=135
  _GENERICNOTIFICATIONMESSAGE._serialized_end=203
# @@protoc_insertion_point(module_scope)
