# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/genericnotification/message/GenericNotificationAck.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMaap_protobuf/service/genericnotification/message/GenericNotificationAck.proto\x12\x30\x61\x61p_protobuf.service.genericnotification.message\"5\n\x16GenericNotificationAck\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07handled\x18\x02 \x01(\x08\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.genericnotification.message.GenericNotificationAck_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _GENERICNOTIFICATIONACK._serialized_start=131
  _GENERICNOTIFICATIONACK._serialized_end=184
# @@protoc_insertion_point(module_scope)
