# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/genericnotification/message/GenericNotificationUnsubscribe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nUaap_protobuf/service/genericnotification/message/GenericNotificationUnsubscribe.proto\x12\x30\x61\x61p_protobuf.service.genericnotification.message\" \n\x1eGenericNotificationUnsubscribe')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.genericnotification.message.GenericNotificationUnsubscribe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICNOTIFICATIONUNSUBSCRIBE._serialized_start=139
  _GENERICNOTIFICATIONUNSUBSCRIBE._serialized_end=171
# @@protoc_insertion_point(module_scope)
