# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/NavigationStatusMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEaap_protobuf/service/navigationstatus/NavigationStatusMessageId.proto\x12%aap_protobuf.service.navigationstatus*\xd3\x02\n\x19NavigationStatusMessageId\x12\x1e\n\x18INSTRUMENT_CLUSTER_START\x10\x81\x80\x02\x12\x1d\n\x17INSTRUMENT_CLUSTER_STOP\x10\x82\x80\x02\x12*\n$INSTRUMENT_CLUSTER_NAVIGATION_STATUS\x10\x83\x80\x02\x12\x32\n(INSTRUMENT_CLUSTER_NAVIGATION_TURN_EVENT\x10\x84\x80\x02\x1a\x02\x08\x01\x12\x36\n,INSTRUMENT_CLUSTER_NAVIGATION_DISTANCE_EVENT\x10\x85\x80\x02\x1a\x02\x08\x01\x12)\n#INSTRUMENT_CLUSTER_NAVIGATION_STATE\x10\x86\x80\x02\x12\x34\n.INSTRUMENT_CLUSTER_NAVIGATION_CURRENT_POSITION\x10\x87\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.NavigationStatusMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTATUSMESSAGEID.values_by_name["INSTRUMENT_CLUSTER_NAVIGATION_TURN_EVENT"]._options = None
  _NAVIGATIONSTATUSMESSAGEID.values_by_name["INSTRUMENT_CLUSTER_NAVIGATION_TURN_EVENT"]._serialized_options = b'\010\001'
  _NAVIGATIONSTATUSMESSAGEID.values_by_name["INSTRUMENT_CLUSTER_NAVIGATION_DISTANCE_EVENT"]._options = None
  _NAVIGATIONSTATUSMESSAGEID.values_by_name["INSTRUMENT_CLUSTER_NAVIGATION_DISTANCE_EVENT"]._serialized_options = b'\010\001'
  _NAVIGATIONSTATUSMESSAGEID._serialized_start=113
  _NAVIGATIONSTATUSMESSAGEID._serialized_end=452
# @@protoc_insertion_point(module_scope)
