# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/NavigationStatusService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/navigationstatus/NavigationStatusService.proto\x12%aap_protobuf.service.navigationstatus\"\xf6\x02\n\x17NavigationStatusService\x12\x1b\n\x13minimum_interval_ms\x18\x01 \x02(\x05\x12\x62\n\x04type\x18\x02 \x02(\x0e\x32T.aap_protobuf.service.navigationstatus.NavigationStatusService.InstrumentClusterType\x12\x62\n\rimage_options\x18\x03 \x01(\x0b\x32K.aap_protobuf.service.navigationstatus.NavigationStatusService.ImageOptions\x1aH\n\x0cImageOptions\x12\x0e\n\x06height\x18\x01 \x02(\x05\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x19\n\x11\x63olour_depth_bits\x18\x03 \x02(\x05\",\n\x15InstrumentClusterType\x12\t\n\x05IMAGE\x10\x01\x12\x08\n\x04\x45NUM\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.NavigationStatusService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTATUSSERVICE._serialized_start=111
  _NAVIGATIONSTATUSSERVICE._serialized_end=485
  _NAVIGATIONSTATUSSERVICE_IMAGEOPTIONS._serialized_start=367
  _NAVIGATIONSTATUSSERVICE_IMAGEOPTIONS._serialized_end=439
  _NAVIGATIONSTATUSSERVICE_INSTRUMENTCLUSTERTYPE._serialized_start=441
  _NAVIGATIONSTATUSSERVICE_INSTRUMENTCLUSTERTYPE._serialized_end=485
# @@protoc_insertion_point(module_scope)
