# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/source/message/MicrophoneRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/media/source/message/MicrophoneRequest.proto\x12)aap_protobuf.service.media.source.message\"_\n\x11MicrophoneRequest\x12\x0c\n\x04open\x18\x01 \x02(\x08\x12\x13\n\x0b\x61nc_enabled\x18\x02 \x01(\x08\x12\x12\n\nec_enabled\x18\x03 \x01(\x08\x12\x13\n\x0bmax_unacked\x18\x04 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.source.message.MicrophoneRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MICROPHONEREQUEST._serialized_start=112
  _MICROPHONEREQUEST._serialized_end=207
# @@protoc_insertion_point(module_scope)
