# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/source/message/MicrophoneResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/media/source/message/MicrophoneResponse.proto\x12)aap_protobuf.service.media.source.message\"8\n\x12MicrophoneResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.source.message.MicrophoneResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MICROPHONERESPONSE._serialized_start=113
  _MICROPHONERESPONSE._serialized_end=169
# @@protoc_insertion_point(module_scope)
