# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/MediaSinkService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import MediaCodecType_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_MediaCodecType__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import AudioStreamType_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_AudioStreamType__pb2
from aasdk_proto.aap_protobuf.service.media.shared.message import AudioConfiguration_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_AudioConfiguration__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import VideoConfiguration_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_VideoConfiguration__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import DisplayType_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_DisplayType__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import KeyCode_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_KeyCode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6aap_protobuf/service/media/sink/MediaSinkService.proto\x12\x1f\x61\x61p_protobuf.service.media.sink\x1a>aap_protobuf/service/media/shared/message/MediaCodecType.proto\x1a=aap_protobuf/service/media/sink/message/AudioStreamType.proto\x1a\x42\x61\x61p_protobuf/service/media/shared/message/AudioConfiguration.proto\x1a@aap_protobuf/service/media/sink/message/VideoConfiguration.proto\x1a\x39\x61\x61p_protobuf/service/media/sink/message/DisplayType.proto\x1a\x35\x61\x61p_protobuf/service/media/sink/message/KeyCode.proto\"\xc8\x04\n\x10MediaSinkService\x12h\n\x0e\x61vailable_type\x18\x01 \x01(\x0e\x32\x39.aap_protobuf.service.media.shared.message.MediaCodecType:\x15MEDIA_CODEC_AUDIO_PCM\x12L\n\naudio_type\x18\x02 \x01(\x0e\x32\x38.aap_protobuf.service.media.sink.message.AudioStreamType\x12T\n\raudio_configs\x18\x03 \x03(\x0b\x32=.aap_protobuf.service.media.shared.message.AudioConfiguration\x12R\n\rvideo_configs\x18\x04 \x03(\x0b\x32;.aap_protobuf.service.media.sink.message.VideoConfiguration\x12\x1f\n\x17\x61vailable_while_in_call\x18\x05 \x01(\x08\x12\x12\n\ndisplay_id\x18\x06 \x01(\r\x12J\n\x0c\x64isplay_type\x18\x07 \x01(\x0e\x32\x34.aap_protobuf.service.media.sink.message.DisplayType\x12Q\n\x17initial_content_keycode\x18\x08 \x01(\x0e\x32\x30.aap_protobuf.service.media.sink.message.KeyCode')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.MediaSinkService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIASINKSERVICE._serialized_start=467
  _MEDIASINKSERVICE._serialized_end=1051
# @@protoc_insertion_point(module_scope)
