# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/MediaMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4aap_protobuf/service/media/sink/MediaMessageId.proto\x12\x1f\x61\x61p_protobuf.service.media.sink*\x81\x04\n\x0eMediaMessageId\x12\x16\n\x12MEDIA_MESSAGE_DATA\x10\x00\x12\x1e\n\x1aMEDIA_MESSAGE_CODEC_CONFIG\x10\x01\x12\x19\n\x13MEDIA_MESSAGE_SETUP\x10\x80\x80\x02\x12\x19\n\x13MEDIA_MESSAGE_START\x10\x81\x80\x02\x12\x18\n\x12MEDIA_MESSAGE_STOP\x10\x82\x80\x02\x12\x1a\n\x14MEDIA_MESSAGE_CONFIG\x10\x83\x80\x02\x12\x17\n\x11MEDIA_MESSAGE_ACK\x10\x84\x80\x02\x12&\n MEDIA_MESSAGE_MICROPHONE_REQUEST\x10\x85\x80\x02\x12\'\n!MEDIA_MESSAGE_MICROPHONE_RESPONSE\x10\x86\x80\x02\x12\'\n!MEDIA_MESSAGE_VIDEO_FOCUS_REQUEST\x10\x87\x80\x02\x12,\n&MEDIA_MESSAGE_VIDEO_FOCUS_NOTIFICATION\x10\x88\x80\x02\x12,\n&MEDIA_MESSAGE_UPDATE_UI_CONFIG_REQUEST\x10\x89\x80\x02\x12*\n$MEDIA_MESSAGE_UPDATE_UI_CONFIG_REPLY\x10\x8a\x80\x02\x12\x30\n*MEDIA_MESSAGE_AUDIO_UNDERFLOW_NOTIFICATION\x10\x8b\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.MediaMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAMESSAGEID._serialized_start=90
  _MEDIAMESSAGEID._serialized_end=603
# @@protoc_insertion_point(module_scope)
