# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/AudioUnderflowNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHaap_protobuf/service/media/sink/message/AudioUnderflowNotification.proto\x12\'aap_protobuf.service.media.sink.message\"0\n\x1a\x41udioUnderflowNotification\x12\x12\n\nsession_id\x18\x01 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.AudioUnderflowNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOUNDERFLOWNOTIFICATION._serialized_start=117
  _AUDIOUNDERFLOWNOTIFICATION._serialized_end=165
# @@protoc_insertion_point(module_scope)
