# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/KeyBindingRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/media/sink/message/KeyBindingRequest.proto\x12\'aap_protobuf.service.media.sink.message\")\n\x11KeyBindingRequest\x12\x14\n\x08keycodes\x18\x01 \x03(\x05\x42\x02\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.KeyBindingRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYBINDINGREQUEST.fields_by_name['keycodes']._options = None
  _KEYBINDINGREQUEST.fields_by_name['keycodes']._serialized_options = b'\020\001'
  _KEYBINDINGREQUEST._serialized_start=108
  _KEYBINDINGREQUEST._serialized_end=149
# @@protoc_insertion_point(module_scope)
