# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/VideoFrameRateType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@aap_protobuf/service/media/sink/message/VideoFrameRateType.proto\x12\'aap_protobuf.service.media.sink.message*8\n\x12VideoFrameRateType\x12\x10\n\x0cVIDEO_FPS_60\x10\x01\x12\x10\n\x0cVIDEO_FPS_30\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.VideoFrameRateType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOFRAMERATETYPE._serialized_start=109
  _VIDEOFRAMERATETYPE._serialized_end=165
# @@protoc_insertion_point(module_scope)
