# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/VideoConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import MediaCodecType_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_MediaCodecType__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import VideoFrameRateType_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_VideoFrameRateType__pb2
from aasdk_proto.aap_protobuf.service.media.sink.message import VideoCodecResolutionType_pb2 as aap__protobuf_dot_service_dot_media_dot_sink_dot_message_dot_VideoCodecResolutionType__pb2
from aasdk_proto.aap_protobuf.service.media.shared.message import UiConfig_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_UiConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@aap_protobuf/service/media/sink/message/VideoConfiguration.proto\x12\'aap_protobuf.service.media.sink.message\x1a>aap_protobuf/service/media/shared/message/MediaCodecType.proto\x1a@aap_protobuf/service/media/sink/message/VideoFrameRateType.proto\x1a\x46\x61\x61p_protobuf/service/media/sink/message/VideoCodecResolutionType.proto\x1a\x38\x61\x61p_protobuf/service/media/shared/message/UiConfig.proto\"\x8e\x04\n\x12VideoConfiguration\x12[\n\x10\x63odec_resolution\x18\x01 \x01(\x0e\x32\x41.aap_protobuf.service.media.sink.message.VideoCodecResolutionType\x12O\n\nframe_rate\x18\x02 \x01(\x0e\x32;.aap_protobuf.service.media.sink.message.VideoFrameRateType\x12\x14\n\x0cwidth_margin\x18\x03 \x01(\r\x12\x15\n\rheight_margin\x18\x04 \x01(\r\x12\x0f\n\x07\x64\x65nsity\x18\x05 \x01(\r\x12 \n\x18\x64\x65\x63oder_additional_depth\x18\x06 \x01(\r\x12\x18\n\x10viewing_distance\x18\x07 \x01(\r\x12\x1d\n\x15pixel_aspect_ratio_e4\x18\x08 \x01(\r\x12\x14\n\x0creal_density\x18\t \x01(\r\x12S\n\x10video_codec_type\x18\n \x01(\x0e\x32\x39.aap_protobuf.service.media.shared.message.MediaCodecType\x12\x46\n\tui_config\x18\x0b \x01(\x0b\x32\x33.aap_protobuf.service.media.shared.message.UiConfig')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.VideoConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOCONFIGURATION._serialized_start=370
  _VIDEOCONFIGURATION._serialized_end=896
# @@protoc_insertion_point(module_scope)
