# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/InputMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aap_protobuf/service/inputsource/InputMessageId.proto\x12 aap_protobuf.service.inputsource*\xa9\x01\n\x0eInputMessageId\x12 \n\x1aINPUT_MESSAGE_INPUT_REPORT\x10\x81\x80\x02\x12\'\n!INPUT_MESSAGE_KEY_BINDING_REQUEST\x10\x82\x80\x02\x12(\n\"INPUT_MESSAGE_KEY_BINDING_RESPONSE\x10\x83\x80\x02\x12\"\n\x1cINPUT_MESSAGE_INPUT_FEEDBACK\x10\x84\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.InputMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTMESSAGEID._serialized_start=92
  _INPUTMESSAGEID._serialized_end=261
# @@protoc_insertion_point(module_scope)
