# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/DeadReckoningData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/sensorsource/message/DeadReckoningData.proto\x12)aap_protobuf.service.sensorsource.message\"F\n\x11\x44\x65\x61\x64ReckoningData\x12\x19\n\x11steering_angle_e1\x18\x01 \x01(\x05\x12\x16\n\x0ewheel_speed_e3\x18\x02 \x03(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.DeadReckoningData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEADRECKONINGDATA._serialized_start=112
  _DEADRECKONINGDATA._serialized_end=182
# @@protoc_insertion_point(module_scope)
