# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/EnvironmentData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/sensorsource/message/EnvironmentData.proto\x12)aap_protobuf.service.sensorsource.message\"L\n\x0f\x45nvironmentData\x12\x16\n\x0etemperature_e3\x18\x01 \x01(\x05\x12\x13\n\x0bpressure_e3\x18\x02 \x01(\x05\x12\x0c\n\x04rain\x18\x03 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.EnvironmentData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENVIRONMENTDATA._serialized_start=110
  _ENVIRONMENTDATA._serialized_end=186
# @@protoc_insertion_point(module_scope)
