# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/EvConnectorType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/sensorsource/message/EvConnectorType.proto\x12)aap_protobuf.service.sensorsource.message*\xfc\x02\n\x0f\x45vConnectorType\x12\x1d\n\x19\x45V_CONNECTOR_TYPE_UNKNOWN\x10\x00\x12\x1b\n\x17\x45V_CONNECTOR_TYPE_J1772\x10\x01\x12\x1e\n\x1a\x45V_CONNECTOR_TYPE_MENNEKES\x10\x02\x12\x1d\n\x19\x45V_CONNECTOR_TYPE_CHADEMO\x10\x03\x12\x1d\n\x19\x45V_CONNECTOR_TYPE_COMBO_1\x10\x04\x12\x1d\n\x19\x45V_CONNECTOR_TYPE_COMBO_2\x10\x05\x12(\n EV_CONNECTOR_TYPE_TESLA_ROADSTER\x10\x06\x1a\x02\x08\x01\x12$\n\x1c\x45V_CONNECTOR_TYPE_TESLA_HPWC\x10\x07\x1a\x02\x08\x01\x12(\n$EV_CONNECTOR_TYPE_TESLA_SUPERCHARGER\x10\x08\x12\x19\n\x15\x45V_CONNECTOR_TYPE_GBT\x10\t\x12\x1b\n\x17\x45V_CONNECTOR_TYPE_OTHER\x10\x65')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.EvConnectorType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVCONNECTORTYPE.values_by_name["EV_CONNECTOR_TYPE_TESLA_ROADSTER"]._options = None
  _EVCONNECTORTYPE.values_by_name["EV_CONNECTOR_TYPE_TESLA_ROADSTER"]._serialized_options = b'\010\001'
  _EVCONNECTORTYPE.values_by_name["EV_CONNECTOR_TYPE_TESLA_HPWC"]._options = None
  _EVCONNECTORTYPE.values_by_name["EV_CONNECTOR_TYPE_TESLA_HPWC"]._serialized_options = b'\010\001'
  _EVCONNECTORTYPE._serialized_start=111
  _EVCONNECTORTYPE._serialized_end=491
# @@protoc_insertion_point(module_scope)
