# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/FuelData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/sensorsource/message/FuelData.proto\x12)aap_protobuf.service.sensorsource.message\"G\n\x08\x46uelData\x12\x12\n\nfuel_level\x18\x01 \x01(\x05\x12\r\n\x05range\x18\x02 \x01(\x05\x12\x18\n\x10low_fuel_warning\x18\x03 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.FuelData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUELDATA._serialized_start=103
  _FUELDATA._serialized_end=174
# @@protoc_insertion_point(module_scope)
