# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/Gear.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4aap_protobuf/service/sensorsource/message/Gear.proto\x12)aap_protobuf.service.sensorsource.message*\xc2\x01\n\x04Gear\x12\x10\n\x0cGEAR_NEUTRAL\x10\x00\x12\n\n\x06GEAR_1\x10\x01\x12\n\n\x06GEAR_2\x10\x02\x12\n\n\x06GEAR_3\x10\x03\x12\n\n\x06GEAR_4\x10\x04\x12\n\n\x06GEAR_5\x10\x05\x12\n\n\x06GEAR_6\x10\x06\x12\n\n\x06GEAR_7\x10\x07\x12\n\n\x06GEAR_8\x10\x08\x12\n\n\x06GEAR_9\x10\t\x12\x0b\n\x07GEAR_10\x10\n\x12\x0e\n\nGEAR_DRIVE\x10\x64\x12\r\n\tGEAR_PARK\x10\x65\x12\x10\n\x0cGEAR_REVERSE\x10\x66')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.Gear_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEAR._serialized_start=100
  _GEAR._serialized_end=294
# @@protoc_insertion_point(module_scope)
