# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/GpsSatellite.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/sensorsource/message/GpsSatellite.proto\x12)aap_protobuf.service.sensorsource.message\"j\n\x0cGpsSatellite\x12\x0b\n\x03prn\x18\x01 \x02(\x05\x12\x0e\n\x06snr_e3\x18\x02 \x02(\x05\x12\x13\n\x0bused_in_fix\x18\x03 \x02(\x08\x12\x12\n\nazimuth_e3\x18\x04 \x01(\x05\x12\x14\n\x0c\x65levation_e3\x18\x05 \x01(\x05\"\x8e\x01\n\x10GpsSatelliteData\x12\x15\n\rnumber_in_use\x18\x01 \x02(\x05\x12\x16\n\x0enumber_in_view\x18\x02 \x01(\x05\x12K\n\nsatellites\x18\x03 \x03(\x0b\x32\x37.aap_protobuf.service.sensorsource.message.GpsSatellite')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.GpsSatellite_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GPSSATELLITE._serialized_start=107
  _GPSSATELLITE._serialized_end=213
  _GPSSATELLITEDATA._serialized_start=216
  _GPSSATELLITEDATA._serialized_end=358
# @@protoc_insertion_point(module_scope)
