# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/LightData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.sensorsource.message import HeadLightState_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_HeadLightState__pb2
from aasdk_proto.aap_protobuf.service.sensorsource.message import TurnIndicatorState_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_TurnIndicatorState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/sensorsource/message/LightData.proto\x12)aap_protobuf.service.sensorsource.message\x1a>aap_protobuf/service/sensorsource/message/HeadLightState.proto\x1a\x42\x61\x61p_protobuf/service/sensorsource/message/TurnIndicatorState.proto\"\xd7\x01\n\tLightData\x12S\n\x10head_light_state\x18\x01 \x01(\x0e\x32\x39.aap_protobuf.service.sensorsource.message.HeadLightState\x12[\n\x14turn_indicator_state\x18\x02 \x01(\x0e\x32=.aap_protobuf.service.sensorsource.message.TurnIndicatorState\x12\x18\n\x10hazard_lights_on\x18\x03 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.LightData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTDATA._serialized_start=237
  _LIGHTDATA._serialized_end=452
# @@protoc_insertion_point(module_scope)
