# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WifiSecurityResponseMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!WifiSecurityResponseMessage.proto\x12\x14\x61\x61sdk.proto.messages\"\xf2\x03\n\x14WifiSecurityResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12N\n\rsecurity_mode\x18\x02 \x01(\x0e\x32\x37.aasdk.proto.messages.WifiSecurityResponse.SecurityMode\x12\x0c\n\x04ssid\x18\x03 \x01(\t\x12\x1f\n\x17supported_wifi_channels\x18\x04 \x03(\x05\x12U\n\x11\x61\x63\x63\x65ss_point_type\x18\x05 \x01(\x0e\x32:.aasdk.proto.messages.WifiSecurityResponse.AccessPointType\"\xca\x01\n\x0cSecurityMode\x12\x19\n\x15UNKNOWN_SECURITY_MODE\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06WEP_64\x10\x02\x12\x0b\n\x07WEP_128\x10\x03\x12\x10\n\x0cWPA_PERSONAL\x10\x04\x12\x11\n\rWPA2_PERSONAL\x10\x08\x12\x15\n\x11WPA_WPA2_PERSONAL\x10\x0c\x12\x12\n\x0eWPA_ENTERPRISE\x10\x14\x12\x13\n\x0fWPA2_ENTERPRISE\x10\x18\x12\x17\n\x13WPA_WPA2_ENTERPRISE\x10\x1c\"*\n\x0f\x41\x63\x63\x65ssPointType\x12\n\n\x06STATIC\x10\x00\x12\x0b\n\x07\x44YNAMIC\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WifiSecurityResponseMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFISECURITYRESPONSE._serialized_start=60
  _WIFISECURITYRESPONSE._serialized_end=558
  _WIFISECURITYRESPONSE_SECURITYMODE._serialized_start=312
  _WIFISECURITYRESPONSE_SECURITYMODE._serialized_end=514
  _WIFISECURITYRESPONSE_ACCESSPOINTTYPE._serialized_start=516
  _WIFISECURITYRESPONSE_ACCESSPOINTTYPE._serialized_end=558
# @@protoc_insertion_point(module_scope)
