# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WifiInfoRequestMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cWifiInfoRequestMessage.proto\x12\x14\x61\x61sdk.proto.messages\"3\n\x0fWifiInfoRequest\x12\x12\n\nip_address\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WifiInfoRequestMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIINFOREQUEST._serialized_start=54
  _WIFIINFOREQUEST._serialized_end=105
# @@protoc_insertion_point(module_scope)
