# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/DisplayType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/media/sink/message/DisplayType.proto\x12\'aap_protobuf.service.media.sink.message*Z\n\x0b\x44isplayType\x12\x15\n\x11\x44ISPLAY_TYPE_MAIN\x10\x00\x12\x18\n\x14\x44ISPLAY_TYPE_CLUSTER\x10\x01\x12\x1a\n\x16\x44ISPLAY_TYPE_AUXILIARY\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.DisplayType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPLAYTYPE._serialized_start=102
  _DISPLAYTYPE._serialized_end=192
# @@protoc_insertion_point(module_scope)
