# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/sink/message/VideoCodecResolutionType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/service/media/sink/message/VideoCodecResolutionType.proto\x12\'aap_protobuf.service.media.sink.message*\xd3\x01\n\x18VideoCodecResolutionType\x12\x11\n\rVIDEO_800x480\x10\x01\x12\x12\n\x0eVIDEO_1280x720\x10\x02\x12\x13\n\x0fVIDEO_1920x1080\x10\x03\x12\x13\n\x0fVIDEO_2560x1440\x10\x04\x12\x13\n\x0fVIDEO_3840x2160\x10\x05\x12\x12\n\x0eVIDEO_720x1280\x10\x06\x12\x13\n\x0fVIDEO_1080x1920\x10\x07\x12\x13\n\x0fVIDEO_1440x2560\x10\x08\x12\x13\n\x0fVIDEO_2160x3840\x10\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.sink.message.VideoCodecResolutionType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOCODECRESOLUTIONTYPE._serialized_start=116
  _VIDEOCODECRESOLUTIONTYPE._serialized_end=327
# @@protoc_insertion_point(module_scope)
