# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/phonestatus/message/PhoneStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/phonestatus/message/PhoneStatus.proto\x12(aap_protobuf.service.phonestatus.message\"\xb3\x03\n\x0bPhoneStatus\x12I\n\x05\x63\x61lls\x18\x01 \x03(\x0b\x32:.aap_protobuf.service.phonestatus.message.PhoneStatus.Call\x12\x17\n\x0fsignal_strength\x18\x02 \x01(\r\x1a\xd7\x01\n\x04\x43\x61ll\x12P\n\x0bphone_state\x18\x01 \x02(\x0e\x32;.aap_protobuf.service.phonestatus.message.PhoneStatus.State\x12\x1d\n\x15\x63\x61ll_duration_seconds\x18\x02 \x02(\r\x12\x15\n\rcaller_number\x18\x03 \x01(\t\x12\x11\n\tcaller_id\x18\x04 \x01(\t\x12\x1a\n\x12\x63\x61ller_number_type\x18\x05 \x01(\t\x12\x18\n\x10\x63\x61ller_thumbnail\x18\x06 \x01(\x0c\"f\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07IN_CALL\x10\x01\x12\x0b\n\x07ON_HOLD\x10\x02\x12\x0c\n\x08INACTIVE\x10\x03\x12\x0c\n\x08INCOMING\x10\x04\x12\x0f\n\x0b\x43ONFERENCED\x10\x05\x12\t\n\x05MUTED\x10\x06')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.phonestatus.message.PhoneStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHONESTATUS._serialized_start=105
  _PHONESTATUS._serialized_end=540
  _PHONESTATUS_CALL._serialized_start=221
  _PHONESTATUS_CALL._serialized_end=436
  _PHONESTATUS_STATE._serialized_start=438
  _PHONESTATUS_STATE._serialized_end=540
# @@protoc_insertion_point(module_scope)
