# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/phonestatus/message/PhoneStatusInput.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import InstrumentClusterInput_pb2 as aap__protobuf_dot_shared_dot_InstrumentClusterInput__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/phonestatus/message/PhoneStatusInput.proto\x12(aap_protobuf.service.phonestatus.message\x1a\x30\x61\x61p_protobuf/shared/InstrumentClusterInput.proto\"x\n\x10PhoneStatusInput\x12:\n\x05input\x18\x01 \x02(\x0b\x32+.aap_protobuf.shared.InstrumentClusterInput\x12\x15\n\rcaller_number\x18\x02 \x01(\t\x12\x11\n\tcaller_id\x18\x03 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.phonestatus.message.PhoneStatusInput_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHONESTATUSINPUT._serialized_start=159
  _PHONESTATUSINPUT._serialized_end=279
# @@protoc_insertion_point(module_scope)
