# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/shared/InstrumentClusterInput.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0aap_protobuf/shared/InstrumentClusterInput.proto\x12\x13\x61\x61p_protobuf.shared\"\xdb\x01\n\x16InstrumentClusterInput\x12S\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x43.aap_protobuf.shared.InstrumentClusterInput.InstrumentClusterAction\"l\n\x17InstrumentClusterAction\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\t\n\x05RIGHT\x10\x04\x12\t\n\x05\x45NTER\x10\x05\x12\x08\n\x04\x42\x41\x43K\x10\x06\x12\x08\n\x04\x43\x41LL\x10\x07')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.shared.InstrumentClusterInput_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUMENTCLUSTERINPUT._serialized_start=74
  _INSTRUMENTCLUSTERINPUT._serialized_end=293
  _INSTRUMENTCLUSTERINPUT_INSTRUMENTCLUSTERACTION._serialized_start=185
  _INSTRUMENTCLUSTERINPUT_INSTRUMENTCLUSTERACTION._serialized_end=293
# @@protoc_insertion_point(module_scope)
