# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/shared/PhoneInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#aap_protobuf/shared/PhoneInfo.proto\x12\x13\x61\x61p_protobuf.shared\"B\n\tPhoneInfo\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12 \n\x18\x63onnectivity_lifetime_id\x18\x02 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.shared.PhoneInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHONEINFO._serialized_start=60
  _PHONEINFO._serialized_end=126
# @@protoc_insertion_point(module_scope)
