# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/bluetooth/message/BluetoothAuthenticationData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.bluetooth.message import BluetoothPairingMethod_pb2 as aap__protobuf_dot_service_dot_bluetooth_dot_message_dot_BluetoothPairingMethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHaap_protobuf/service/bluetooth/message/BluetoothAuthenticationData.proto\x12&aap_protobuf.service.bluetooth.message\x1a\x43\x61\x61p_protobuf/service/bluetooth/message/BluetoothPairingMethod.proto\"\x88\x01\n\x1b\x42luetoothAuthenticationData\x12\x11\n\tauth_data\x18\x01 \x02(\t\x12V\n\x0epairing_method\x18\x02 \x01(\x0e\x32>.aap_protobuf.service.bluetooth.message.BluetoothPairingMethod')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.bluetooth.message.BluetoothAuthenticationData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLUETOOTHAUTHENTICATIONDATA._serialized_start=186
  _BLUETOOTHAUTHENTICATIONDATA._serialized_end=322
# @@protoc_insertion_point(module_scope)
