# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/MediaBrowserMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/mediabrowser/MediaBrowserMessageId.proto\x12!aap_protobuf.service.mediabrowser*\xa5\x01\n\x15MediaBrowserMessageId\x12\x15\n\x0fMEDIA_ROOT_NODE\x10\x81\x80\x02\x12\x17\n\x11MEDIA_SOURCE_NODE\x10\x82\x80\x02\x12\x15\n\x0fMEDIA_LIST_NODE\x10\x83\x80\x02\x12\x15\n\x0fMEDIA_SONG_NODE\x10\x84\x80\x02\x12\x14\n\x0eMEDIA_GET_NODE\x10\x85\x80\x02\x12\x18\n\x12MEDIA_BROWSE_INPUT\x10\x86\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.MediaBrowserMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIABROWSERMESSAGEID._serialized_start=101
  _MEDIABROWSERMESSAGEID._serialized_end=266
# @@protoc_insertion_point(module_scope)
