# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediaplayback/MediaPlaybackStatusMessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEaap_protobuf/service/mediaplayback/MediaPlaybackStatusMessageId.proto\x12\"aap_protobuf.service.mediaplayback*v\n\x1cMediaPlaybackStatusMessageId\x12\x1b\n\x15MEDIA_PLAYBACK_STATUS\x10\x81\x80\x02\x12\x1a\n\x14MEDIA_PLAYBACK_INPUT\x10\x82\x80\x02\x12\x1d\n\x17MEDIA_PLAYBACK_METADATA\x10\x83\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediaplayback.MediaPlaybackStatusMessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAPLAYBACKSTATUSMESSAGEID._serialized_start=109
  _MEDIAPLAYBACKSTATUSMESSAGEID._serialized_end=227
# @@protoc_insertion_point(module_scope)
