# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/GetTrafficUpdateResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import MessageStatus_pb2 as aap__protobuf_dot_shared_dot_MessageStatus__pb2
from aasdk_proto.aap_protobuf.service.radio.message import TrafficIncident_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_TrafficIncident__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/radio/message/GetTrafficUpdateResponse.proto\x12\"aap_protobuf.service.radio.message\x1a\'aap_protobuf/shared/MessageStatus.proto\x1a\x38\x61\x61p_protobuf/service/radio/message/TrafficIncident.proto\"\xa8\x01\n\x18GetTrafficUpdateResponse\x12\x32\n\x06status\x18\x01 \x02(\x0e\x32\".aap_protobuf.shared.MessageStatus\x12\x10\n\x08radio_id\x18\x02 \x02(\x05\x12\x46\n\tincidents\x18\x03 \x03(\x0b\x32\x33.aap_protobuf.service.radio.message.TrafficIncidentB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.GetTrafficUpdateResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _GETTRAFFICUPDATERESPONSE._serialized_start=205
  _GETTRAFFICUPDATERESPONSE._serialized_end=373
# @@protoc_insertion_point(module_scope)
