# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/HdRadioSisData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import Location_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_Location__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/radio/message/HdRadioSisData.proto\x12\"aap_protobuf.service.radio.message\x1a\x31\x61\x61p_protobuf/service/radio/message/Location.proto\"\x87\x02\n\x0eHdRadioSisData\x12\x12\n\nstation_id\x18\x01 \x01(\x05\x12\x1a\n\x12station_name_short\x18\x02 \x01(\t\x12\x19\n\x11station_name_long\x18\x03 \x01(\t\x12\x46\n\x10station_location\x18\x04 \x01(\x0b\x32,.aap_protobuf.service.radio.message.Location\x12\x17\n\x0fstation_message\x18\x05 \x01(\t\x12\x1c\n\x14service_info_message\x18\x06 \x01(\t\x12+\n#universal_short_station_name_slogan\x18\x07 \x01(\tB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.HdRadioSisData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _HDRADIOSISDATA._serialized_start=147
  _HDRADIOSISDATA._serialized_end=410
# @@protoc_insertion_point(module_scope)
