# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/ItuRegion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2aap_protobuf/service/radio/message/ItuRegion.proto\x12\x1a\x61\x61p_protobuf.service.radio*\x99\x01\n\tItuRegion\x12\x15\n\x11RADIO_REGION_NONE\x10\x00\x12\x16\n\x12RADIO_REGION_ITU_1\x10\x01\x12\x16\n\x12RADIO_REGION_ITU_2\x10\x02\x12\x15\n\x11RADIO_REGION_OIRT\x10\x03\x12\x16\n\x12RADIO_REGION_JAPAN\x10\x04\x12\x16\n\x12RADIO_REGION_KOREA\x10\x05\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.ItuRegion_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _ITUREGION._serialized_start=83
  _ITUREGION._serialized_end=236
# @@protoc_insertion_point(module_scope)
