# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/MuteRadioResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import MessageStatus_pb2 as aap__protobuf_dot_shared_dot_MessageStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/radio/message/MuteRadioResponse.proto\x12\"aap_protobuf.service.radio.message\x1a\'aap_protobuf/shared/MessageStatus.proto\"h\n\x11MuteRadioResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".aap_protobuf.shared.MessageStatus\x12\x10\n\x08radio_id\x18\x02 \x01(\x05\x12\r\n\x05muted\x18\x03 \x01(\x08\x42\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.MuteRadioResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _MUTERADIORESPONSE._serialized_start=139
  _MUTERADIORESPONSE._serialized_end=243
# @@protoc_insertion_point(module_scope)
