# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/radio/message/StationPresetList.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.radio.message import StationPreset_pb2 as aap__protobuf_dot_service_dot_radio_dot_message_dot_StationPreset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/radio/message/StationPresetList.proto\x12\"aap_protobuf.service.radio.message\x1a\x36\x61\x61p_protobuf/service/radio/message/StationPreset.proto\"\x87\x01\n\x11StationPresetList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x18restricted_station_types\x18\x02 \x03(\x05\x12\x42\n\x07presets\x18\x03 \x03(\x0b\x32\x31.aap_protobuf.service.radio.message.StationPresetB\x02H\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.radio.message.StationPresetList_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _STATIONPRESETLIST._serialized_start=155
  _STATIONPRESETLIST._serialized_end=290
# @@protoc_insertion_point(module_scope)
