# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/FuelType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/sensorsource/message/FuelType.proto\x12)aap_protobuf.service.sensorsource.message*\xa9\x02\n\x08\x46uelType\x12\x15\n\x11\x46UEL_TYPE_UNKNOWN\x10\x00\x12\x16\n\x12\x46UEL_TYPE_UNLEADED\x10\x01\x12\x14\n\x10\x46UEL_TYPE_LEADED\x10\x02\x12\x16\n\x12\x46UEL_TYPE_DIESEL_1\x10\x03\x12\x16\n\x12\x46UEL_TYPE_DIESEL_2\x10\x04\x12\x17\n\x13\x46UEL_TYPE_BIODIESEL\x10\x05\x12\x11\n\rFUEL_TYPE_E85\x10\x06\x12\x11\n\rFUEL_TYPE_LPG\x10\x07\x12\x11\n\rFUEL_TYPE_CNG\x10\x08\x12\x11\n\rFUEL_TYPE_LNG\x10\t\x12\x16\n\x12\x46UEL_TYPE_ELECTRIC\x10\n\x12\x16\n\x12\x46UEL_TYPE_HYDROGEN\x10\x0b\x12\x13\n\x0f\x46UEL_TYPE_OTHER\x10\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.FuelType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUELTYPE._serialized_start=104
  _FUELTYPE._serialized_end=401
# @@protoc_insertion_point(module_scope)
