# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/GearData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.sensorsource.message import Gear_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_Gear__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/sensorsource/message/GearData.proto\x12)aap_protobuf.service.sensorsource.message\x1a\x34\x61\x61p_protobuf/service/sensorsource/message/Gear.proto\"I\n\x08GearData\x12=\n\x04gear\x18\x01 \x02(\x0e\x32/.aap_protobuf.service.sensorsource.message.Gear')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.GearData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEARDATA._serialized_start=157
  _GEARDATA._serialized_end=230
# @@protoc_insertion_point(module_scope)
