# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/GyroscopeData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/sensorsource/message/GyroscopeData.proto\x12)aap_protobuf.service.sensorsource.message\"f\n\rGyroscopeData\x12\x1b\n\x13rotation_speed_x_e3\x18\x01 \x01(\x05\x12\x1b\n\x13rotation_speed_y_e3\x18\x02 \x01(\x05\x12\x1b\n\x13rotation_speed_z_e3\x18\x03 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.GyroscopeData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GYROSCOPEDATA._serialized_start=108
  _GYROSCOPEDATA._serialized_end=210
# @@protoc_insertion_point(module_scope)
