# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/HeadLightState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/sensorsource/message/HeadLightState.proto\x12)aap_protobuf.service.sensorsource.message*^\n\x0eHeadLightState\x12\x18\n\x14HEAD_LIGHT_STATE_OFF\x10\x01\x12\x17\n\x13HEAD_LIGHT_STATE_ON\x10\x02\x12\x19\n\x15HEAD_LIGHT_STATE_HIGH\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.HeadLightState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADLIGHTSTATE._serialized_start=109
  _HEADLIGHTSTATE._serialized_end=203
# @@protoc_insertion_point(module_scope)
