# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/LocationData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/sensorsource/message/LocationData.proto\x12)aap_protobuf.service.sensorsource.message\"\xa0\x01\n\x0cLocationData\x12\x15\n\ttimestamp\x18\x01 \x01(\x04\x42\x02\x18\x01\x12\x13\n\x0blatitude_e7\x18\x02 \x02(\x05\x12\x14\n\x0clongitude_e7\x18\x03 \x02(\x05\x12\x13\n\x0b\x61\x63\x63uracy_e3\x18\x04 \x01(\r\x12\x13\n\x0b\x61ltitude_e2\x18\x05 \x01(\x05\x12\x10\n\x08speed_e3\x18\x06 \x01(\x05\x12\x12\n\nbearing_e6\x18\x07 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.LocationData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONDATA.fields_by_name['timestamp']._options = None
  _LOCATIONDATA.fields_by_name['timestamp']._serialized_options = b'\030\001'
  _LOCATIONDATA._serialized_start=108
  _LOCATIONDATA._serialized_end=268
# @@protoc_insertion_point(module_scope)
