# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/SensorType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/sensorsource/message/SensorType.proto\x12)aap_protobuf.service.sensorsource.message*\xaa\x04\n\nSensorType\x12\x13\n\x0fSENSOR_LOCATION\x10\x01\x12\x12\n\x0eSENSOR_COMPASS\x10\x02\x12\x10\n\x0cSENSOR_SPEED\x10\x03\x12\x0e\n\nSENSOR_RPM\x10\x04\x12\x13\n\x0fSENSOR_ODOMETER\x10\x05\x12\x0f\n\x0bSENSOR_FUEL\x10\x06\x12\x18\n\x14SENSOR_PARKING_BRAKE\x10\x07\x12\x0f\n\x0bSENSOR_GEAR\x10\x08\x12 \n\x1cSENSOR_OBDII_DIAGNOSTIC_CODE\x10\t\x12\x15\n\x11SENSOR_NIGHT_MODE\x10\n\x12\x1b\n\x17SENSOR_ENVIRONMENT_DATA\x10\x0b\x12\x14\n\x10SENSOR_HVAC_DATA\x10\x0c\x12\x1e\n\x1aSENSOR_DRIVING_STATUS_DATA\x10\r\x12\x1e\n\x1aSENSOR_DEAD_RECKONING_DATA\x10\x0e\x12\x19\n\x15SENSOR_PASSENGER_DATA\x10\x0f\x12\x14\n\x10SENSOR_DOOR_DATA\x10\x10\x12\x15\n\x11SENSOR_LIGHT_DATA\x10\x11\x12\x1d\n\x19SENSOR_TIRE_PRESSURE_DATA\x10\x12\x12\x1d\n\x19SENSOR_ACCELEROMETER_DATA\x10\x13\x12\x19\n\x15SENSOR_GYROSCOPE_DATA\x10\x14\x12\x1d\n\x19SENSOR_GPS_SATELLITE_DATA\x10\x15\x12\x14\n\x10SENSOR_TOLL_CARD\x10\x16')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.SensorType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORTYPE._serialized_start=106
  _SENSORTYPE._serialized_end=660
# @@protoc_insertion_point(module_scope)
