# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/SensorErrorType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?aap_protobuf/service/sensorsource/message/SensorErrorType.proto\x12)aap_protobuf.service.sensorsource.message*X\n\x0fSensorErrorType\x12\r\n\tSENSOR_OK\x10\x01\x12\x1a\n\x16SENSOR_ERROR_TRANSIENT\x10\x02\x12\x1a\n\x16SENSOR_ERROR_PERMANENT\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.SensorErrorType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORERRORTYPE._serialized_start=110
  _SENSORERRORTYPE._serialized_end=198
# @@protoc_insertion_point(module_scope)
