# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/Sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.sensorsource.message import SensorType_pb2 as aap__protobuf_dot_service_dot_sensorsource_dot_message_dot_SensorType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6aap_protobuf/service/sensorsource/message/Sensor.proto\x12)aap_protobuf.service.sensorsource.message\x1a:aap_protobuf/service/sensorsource/message/SensorType.proto\"T\n\x06Sensor\x12J\n\x0bsensor_type\x18\x01 \x02(\x0e\x32\x35.aap_protobuf.service.sensorsource.message.SensorType')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.Sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSOR._serialized_start=161
  _SENSOR._serialized_end=245
# @@protoc_insertion_point(module_scope)
