# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/sensorsource/message/SpeedData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/sensorsource/message/SpeedData.proto\x12)aap_protobuf.service.sensorsource.message\"O\n\tSpeedData\x12\x10\n\x08speed_e3\x18\x01 \x02(\x05\x12\x16\n\x0e\x63ruise_engaged\x18\x02 \x01(\x08\x12\x18\n\x10\x63ruise_set_speed\x18\x04 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.sensorsource.message.SpeedData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEEDDATA._serialized_start=104
  _SPEEDDATA._serialized_end=183
# @@protoc_insertion_point(module_scope)
