# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/InputReport.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.inputsource.message import TouchEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_TouchEvent__pb2
from aasdk_proto.aap_protobuf.service.inputsource.message import AbsoluteEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_AbsoluteEvent__pb2
from aasdk_proto.aap_protobuf.service.inputsource.message import RelativeEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_RelativeEvent__pb2
from aasdk_proto.aap_protobuf.service.inputsource.message import KeyEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_KeyEvent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:aap_protobuf/service/inputsource/message/InputReport.proto\x12(aap_protobuf.service.inputsource.message\x1a\x39\x61\x61p_protobuf/service/inputsource/message/TouchEvent.proto\x1a<aap_protobuf/service/inputsource/message/AbsoluteEvent.proto\x1a<aap_protobuf/service/inputsource/message/RelativeEvent.proto\x1a\x37\x61\x61p_protobuf/service/inputsource/message/KeyEvent.proto\"\xbf\x03\n\x0bInputReport\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x1b\n\x0f\x64isp_channel_id\x18\x02 \x01(\x05\x42\x02\x18\x01\x12I\n\x0btouch_event\x18\x03 \x01(\x0b\x32\x34.aap_protobuf.service.inputsource.message.TouchEvent\x12\x45\n\tkey_event\x18\x04 \x01(\x0b\x32\x32.aap_protobuf.service.inputsource.message.KeyEvent\x12O\n\x0e\x61\x62solute_event\x18\x05 \x01(\x0b\x32\x37.aap_protobuf.service.inputsource.message.AbsoluteEvent\x12O\n\x0erelative_event\x18\x06 \x01(\x0b\x32\x37.aap_protobuf.service.inputsource.message.RelativeEvent\x12L\n\x0etouchpad_event\x18\x07 \x01(\x0b\x32\x34.aap_protobuf.service.inputsource.message.TouchEvent')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.InputReport_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTREPORT.fields_by_name['disp_channel_id']._options = None
  _INPUTREPORT.fields_by_name['disp_channel_id']._serialized_options = b'\030\001'
  _INPUTREPORT._serialized_start=345
  _INPUTREPORT._serialized_end=792
# @@protoc_insertion_point(module_scope)
