# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/TouchEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.inputsource.message import PointerAction_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_PointerAction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/inputsource/message/TouchEvent.proto\x12(aap_protobuf.service.inputsource.message\x1a<aap_protobuf/service/inputsource/message/PointerAction.proto\"\xf4\x01\n\nTouchEvent\x12R\n\x0cpointer_data\x18\x01 \x03(\x0b\x32<.aap_protobuf.service.inputsource.message.TouchEvent.Pointer\x12\x14\n\x0c\x61\x63tion_index\x18\x02 \x01(\r\x12G\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x37.aap_protobuf.service.inputsource.message.PointerAction\x1a\x33\n\x07Pointer\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\x12\n\npointer_id\x18\x03 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.TouchEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOUCHEVENT._serialized_start=166
  _TOUCHEVENT._serialized_end=410
  _TOUCHEVENT_POINTER._serialized_start=359
  _TOUCHEVENT_POINTER._serialized_end=410
# @@protoc_insertion_point(module_scope)
