# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/video/message/VideoFocusMode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/media/video/message/VideoFocusMode.proto\x12(aap_protobuf.service.media.video.message*\x8f\x01\n\x0eVideoFocusMode\x12\x19\n\x15VIDEO_FOCUS_PROJECTED\x10\x01\x12\x16\n\x12VIDEO_FOCUS_NATIVE\x10\x02\x12 \n\x1cVIDEO_FOCUS_NATIVE_TRANSIENT\x10\x03\x12(\n$VIDEO_FOCUS_PROJECTED_NO_INPUT_FOCUS\x10\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.video.message.VideoFocusMode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOFOCUSMODE._serialized_start=108
  _VIDEOFOCUSMODE._serialized_end=251
# @@protoc_insertion_point(module_scope)
