# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/CarConnectedDevices.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import ConnectedDevice_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectedDevice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/control/message/CarConnectedDevices.proto\x12$aap_protobuf.service.control.message\x1a:aap_protobuf/service/control/message/ConnectedDevice.proto\"\x96\x01\n\x13\x43\x61rConnectedDevices\x12P\n\x11\x63onnected_devices\x18\x01 \x03(\x0b\x32\x35.aap_protobuf.service.control.message.ConnectedDevice\x12\x13\n\x0bunsolicited\x18\x02 \x01(\x08\x12\x18\n\nfinal_list\x18\x03 \x01(\x08:\x04true')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.CarConnectedDevices_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARCONNECTEDDEVICES._serialized_start=165
  _CARCONNECTEDDEVICES._serialized_end=315
# @@protoc_insertion_point(module_scope)
