# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ConnectionConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import PingConfiguration_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_PingConfiguration__pb2
from aasdk_proto.aap_protobuf.service.control.message import WirelessTcpConfiguration_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_WirelessTcpConfiguration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/control/message/ConnectionConfiguration.proto\x12$aap_protobuf.service.control.message\x1a<aap_protobuf/service/control/message/PingConfiguration.proto\x1a\x43\x61\x61p_protobuf/service/control/message/WirelessTcpConfiguration.proto\"\xd2\x01\n\x17\x43onnectionConfiguration\x12S\n\x12ping_configuration\x18\x01 \x01(\x0b\x32\x37.aap_protobuf.service.control.message.PingConfiguration\x12\x62\n\x1awireless_tcp_configuration\x18\x02 \x01(\x0b\x32>.aap_protobuf.service.control.message.WirelessTcpConfiguration')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ConnectionConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONCONFIGURATION._serialized_start=240
  _CONNECTIONCONFIGURATION._serialized_end=450
# @@protoc_insertion_point(module_scope)
