# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/NavFocusRequestNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import NavFocusType_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_NavFocusType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFaap_protobuf/service/control/message/NavFocusRequestNotification.proto\x12$aap_protobuf.service.control.message\x1a\x37\x61\x61p_protobuf/service/control/message/NavFocusType.proto\"e\n\x1bNavFocusRequestNotification\x12\x46\n\nfocus_type\x18\x01 \x01(\x0e\x32\x32.aap_protobuf.service.control.message.NavFocusType')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.NavFocusRequestNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVFOCUSREQUESTNOTIFICATION._serialized_start=169
  _NAVFOCUSREQUESTNOTIFICATION._serialized_end=270
# @@protoc_insertion_point(module_scope)
