# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ServiceDiscoveryRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import PhoneInfo_pb2 as aap__protobuf_dot_shared_dot_PhoneInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/control/message/ServiceDiscoveryRequest.proto\x12$aap_protobuf.service.control.message\x1a#aap_protobuf/shared/PhoneInfo.proto\"\xb3\x01\n\x17ServiceDiscoveryRequest\x12\x12\n\nsmall_icon\x18\x01 \x01(\x0c\x12\x13\n\x0bmedium_icon\x18\x02 \x01(\x0c\x12\x12\n\nlarge_icon\x18\x03 \x01(\x0c\x12\x12\n\nlabel_text\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x05 \x01(\t\x12\x32\n\nphone_info\x18\x06 \x01(\x0b\x32\x1e.aap_protobuf.shared.PhoneInfo')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ServiceDiscoveryRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICEDISCOVERYREQUEST._serialized_start=146
  _SERVICEDISCOVERYREQUEST._serialized_end=325
# @@protoc_insertion_point(module_scope)
