# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/UserSwitchStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;aap_protobuf/service/control/message/UserSwitchStatus.proto\x12$aap_protobuf.service.control.message*\xa1\x03\n\x10UserSwitchStatus\x12\r\n\tSTATUS_OK\x10\x00\x12\'\n\x1a\x45RROR_NO_RFCOMM_CONNECTION\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12)\n\x1c\x45RROR_BT_CLOSED_BEFORE_START\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12(\n\x1b\x45RROR_BT_CLOSED_AFTER_START\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x36\n)ERROR_INCOMPATIBLE_PHONE_PROTOCOL_VERSION\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12/\n\"ERROR_PHONE_UNABLE_TO_CONNECT_WIFI\x10\xfb\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12/\n\"ERROR_MULTIPLE_USER_SWITCH_REQUEST\x10\xfa\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1e\n\x11\x45RROR_HU_INTERNAL\x10\xf9\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n\x15\x45RROR_INVALID_REQUEST\x10\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n\x15\x45RROR_REQUEST_TIMEOUT\x10\xf7\xff\xff\xff\xff\xff\xff\xff\xff\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.UserSwitchStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERSWITCHSTATUS._serialized_start=102
  _USERSWITCHSTATUS._serialized_end=519
# @@protoc_insertion_point(module_scope)
