# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/UserSwitchRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import ConnectedDevice_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectedDevice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/control/message/UserSwitchRequest.proto\x12$aap_protobuf.service.control.message\x1a:aap_protobuf/service/control/message/ConnectedDevice.proto\"c\n\x11UserSwitchRequest\x12N\n\x0fselected_device\x18\x01 \x01(\x0b\x32\x35.aap_protobuf.service.control.message.ConnectedDevice')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.UserSwitchRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERSWITCHREQUEST._serialized_start=162
  _USERSWITCHREQUEST._serialized_end=261
# @@protoc_insertion_point(module_scope)
