# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/VersionResponseOptions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import ConnectionConfiguration_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectionConfiguration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/control/message/VersionResponseOptions.proto\x12$aap_protobuf.service.control.message\x1a\x42\x61\x61p_protobuf/service/control/message/ConnectionConfiguration.proto\"y\n\x16VersionResponseOptions\x12_\n\x18\x63onnection_configuration\x18\x01 \x01(\x0b\x32=.aap_protobuf.service.control.message.ConnectionConfiguration')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.VersionResponseOptions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERSIONRESPONSEOPTIONS._serialized_start=175
  _VERSIONRESPONSEOPTIONS._serialized_end=296
# @@protoc_insertion_point(module_scope)
