# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/VoiceSessionStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/control/message/VoiceSessionStatus.proto\x12$aap_protobuf.service.control.message*D\n\x12VoiceSessionStatus\x12\x17\n\x13VOICE_SESSION_START\x10\x01\x12\x15\n\x11VOICE_SESSION_END\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.VoiceSessionStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOICESESSIONSTATUS._serialized_start=103
  _VOICESESSIONSTATUS._serialized_end=171
# @@protoc_insertion_point(module_scope)
