# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationNextTurnEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKaap_protobuf/service/navigationstatus/message/NavigationNextTurnEvent.proto\x12-aap_protobuf.service.navigationstatus.message\"\x89\x05\n\x17NavigationNextTurnEvent\x12\x0c\n\x04road\x18\x01 \x02(\t\x12\x62\n\tturn_side\x18\x02 \x01(\x0e\x32O.aap_protobuf.service.navigationstatus.message.NavigationNextTurnEvent.TurnSide\x12\x62\n\x05\x65vent\x18\x03 \x01(\x0e\x32S.aap_protobuf.service.navigationstatus.message.NavigationNextTurnEvent.NextTurnEnum\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x13\n\x0bturn_number\x18\x05 \x01(\x05\x12\x12\n\nturn_angle\x18\x06 \x01(\x05\"0\n\x08TurnSide\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x0f\n\x0bUNSPECIFIED\x10\x03\"\xa9\x02\n\x0cNextTurnEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x44\x45PART\x10\x01\x12\x0f\n\x0bNAME_CHANGE\x10\x02\x12\x0f\n\x0bSLIGHT_TURN\x10\x03\x12\x08\n\x04TURN\x10\x04\x12\x0e\n\nSHARP_TURN\x10\x05\x12\n\n\x06U_TURN\x10\x06\x12\x0b\n\x07ON_RAMP\x10\x07\x12\x0c\n\x08OFF_RAMP\x10\x08\x12\x08\n\x04\x46ORK\x10\t\x12\t\n\x05MERGE\x10\n\x12\x14\n\x10ROUNDABOUT_ENTER\x10\x0b\x12\x13\n\x0fROUNDABOUT_EXIT\x10\x0c\x12\x1d\n\x19ROUNDABOUT_ENTER_AND_EXIT\x10\r\x12\x0c\n\x08STRAIGHT\x10\x0e\x12\x0e\n\nFERRY_BOAT\x10\x10\x12\x0f\n\x0b\x46\x45RRY_TRAIN\x10\x11\x12\x0f\n\x0b\x44\x45STINATION\x10\x13:\x02\x18\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationNextTurnEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONNEXTTURNEVENT._options = None
  _NAVIGATIONNEXTTURNEVENT._serialized_options = b'\030\001'
  _NAVIGATIONNEXTTURNEVENT._serialized_start=127
  _NAVIGATIONNEXTTURNEVENT._serialized_end=776
  _NAVIGATIONNEXTTURNEVENT_TURNSIDE._serialized_start=424
  _NAVIGATIONNEXTTURNEVENT_TURNSIDE._serialized_end=472
  _NAVIGATIONNEXTTURNEVENT_NEXTTURNENUM._serialized_start=475
  _NAVIGATIONNEXTTURNEVENT_NEXTTURNENUM._serialized_end=772
# @@protoc_insertion_point(module_scope)
