# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationStep.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationManeuver_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationManeuver__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationRoad_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationRoad__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationLane_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationLane__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationCue_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationCue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/navigationstatus/message/NavigationStep.proto\x12-aap_protobuf.service.navigationstatus.message\x1a\x46\x61\x61p_protobuf/service/navigationstatus/message/NavigationManeuver.proto\x1a\x42\x61\x61p_protobuf/service/navigationstatus/message/NavigationRoad.proto\x1a\x42\x61\x61p_protobuf/service/navigationstatus/message/NavigationLane.proto\x1a\x41\x61\x61p_protobuf/service/navigationstatus/message/NavigationCue.proto\"\xcb\x02\n\x0eNavigationStep\x12S\n\x08maneuver\x18\x01 \x01(\x0b\x32\x41.aap_protobuf.service.navigationstatus.message.NavigationManeuver\x12K\n\x04road\x18\x02 \x01(\x0b\x32=.aap_protobuf.service.navigationstatus.message.NavigationRoad\x12L\n\x05lanes\x18\x03 \x03(\x0b\x32=.aap_protobuf.service.navigationstatus.message.NavigationLane\x12I\n\x03\x63ue\x18\x04 \x01(\x0b\x32<.aap_protobuf.service.navigationstatus.message.NavigationCue')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationStep_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTEP._serialized_start=393
  _NAVIGATIONSTEP._serialized_end=724
# @@protoc_insertion_point(module_scope)
