# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationStep_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationStep__pb2
from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationDestination_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationDestination__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/navigationstatus/message/NavigationState.proto\x12-aap_protobuf.service.navigationstatus.message\x1a\x42\x61\x61p_protobuf/service/navigationstatus/message/NavigationStep.proto\x1aIaap_protobuf/service/navigationstatus/message/NavigationDestination.proto\"\xbb\x01\n\x0fNavigationState\x12L\n\x05steps\x18\x01 \x03(\x0b\x32=.aap_protobuf.service.navigationstatus.message.NavigationStep\x12Z\n\x0c\x64\x65stinations\x18\x02 \x03(\x0b\x32\x44.aap_protobuf.service.navigationstatus.message.NavigationDestination')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationState_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTATE._serialized_start=262
  _NAVIGATIONSTATE._serialized_end=449
# @@protoc_insertion_point(module_scope)
