# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/navigationstatus/message/NavigationStepDistance.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.navigationstatus.message import NavigationDistance_pb2 as aap__protobuf_dot_service_dot_navigationstatus_dot_message_dot_NavigationDistance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJaap_protobuf/service/navigationstatus/message/NavigationStepDistance.proto\x12-aap_protobuf.service.navigationstatus.message\x1a\x46\x61\x61p_protobuf/service/navigationstatus/message/NavigationDistance.proto\"\x8b\x01\n\x16NavigationStepDistance\x12S\n\x08\x64istance\x18\x01 \x01(\x0b\x32\x41.aap_protobuf.service.navigationstatus.message.NavigationDistance\x12\x1c\n\x14time_to_step_seconds\x18\x02 \x01(\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.navigationstatus.message.NavigationStepDistance_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVIGATIONSTEPDISTANCE._serialized_start=198
  _NAVIGATIONSTEPDISTANCE._serialized_end=337
# @@protoc_insertion_point(module_scope)
