# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/AudioFocusNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import AudioFocusStateType_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_AudioFocusStateType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/control/message/AudioFocusNotification.proto\x12$aap_protobuf.service.control.message\x1a>aap_protobuf/service/control/message/AudioFocusStateType.proto\"}\n\x16\x41udioFocusNotification\x12N\n\x0b\x66ocus_state\x18\x01 \x02(\x0e\x32\x39.aap_protobuf.service.control.message.AudioFocusStateType\x12\x13\n\x0bunsolicited\x18\x02 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.AudioFocusNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOFOCUSNOTIFICATION._serialized_start=171
  _AUDIOFOCUSNOTIFICATION._serialized_end=296
# @@protoc_insertion_point(module_scope)
