# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/AudioFocusRequestType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@aap_protobuf/service/control/message/AudioFocusRequestType.proto\x12$aap_protobuf.service.control.message*\x8f\x01\n\x15\x41udioFocusRequestType\x12\x14\n\x10\x41UDIO_FOCUS_GAIN\x10\x01\x12\x1e\n\x1a\x41UDIO_FOCUS_GAIN_TRANSIENT\x10\x02\x12\'\n#AUDIO_FOCUS_GAIN_TRANSIENT_MAY_DUCK\x10\x03\x12\x17\n\x13\x41UDIO_FOCUS_RELEASE\x10\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.AudioFocusRequestType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOFOCUSREQUESTTYPE._serialized_start=107
  _AUDIOFOCUSREQUESTTYPE._serialized_end=250
# @@protoc_insertion_point(module_scope)
