# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/BatteryStatusNotification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDaap_protobuf/service/control/message/BatteryStatusNotification.proto\x12$aap_protobuf.service.control.message\"f\n\x19\x42\x61tteryStatusNotification\x12\x15\n\rbattery_level\x18\x01 \x02(\r\x12\x18\n\x10time_remaining_s\x18\x02 \x01(\r\x12\x18\n\x10\x63ritical_battery\x18\x03 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.BatteryStatusNotification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTERYSTATUSNOTIFICATION._serialized_start=110
  _BATTERYSTATUSNOTIFICATION._serialized_end=212
# @@protoc_insertion_point(module_scope)
