# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ByeByeReason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/control/message/ByeByeReason.proto\x12$aap_protobuf.service.control.message*z\n\x0c\x42yeByeReason\x12\x12\n\x0eUSER_SELECTION\x10\x01\x12\x11\n\rDEVICE_SWITCH\x10\x02\x12\x11\n\rNOT_SUPPORTED\x10\x03\x12\x1b\n\x17NOT_CURRENTLY_SUPPORTED\x10\x04\x12\x13\n\x0fPROBE_SUPPORTED\x10\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ByeByeReason_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BYEBYEREASON._serialized_start=97
  _BYEBYEREASON._serialized_end=219
# @@protoc_insertion_point(module_scope)
