# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ByeByeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.control.message import ByeByeReason_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ByeByeReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/control/message/ByeByeRequest.proto\x12$aap_protobuf.service.control.message\x1a\x37\x61\x61p_protobuf/service/control/message/ByeByeReason.proto\"S\n\rByeByeRequest\x12\x42\n\x06reason\x18\x01 \x02(\x0e\x32\x32.aap_protobuf.service.control.message.ByeByeReason')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ByeByeRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BYEBYEREQUEST._serialized_start=155
  _BYEBYEREQUEST._serialized_end=238
# @@protoc_insertion_point(module_scope)
