# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ChannelOpenRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/control/message/ChannelOpenRequest.proto\x12$aap_protobuf.service.control.message\":\n\x12\x43hannelOpenRequest\x12\x10\n\x08priority\x18\x01 \x02(\x11\x12\x12\n\nservice_id\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ChannelOpenRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELOPENREQUEST._serialized_start=103
  _CHANNELOPENREQUEST._serialized_end=161
# @@protoc_insertion_point(module_scope)
