# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/FragInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3aap_protobuf/service/control/message/FragInfo.proto\x12$aap_protobuf.service.control.message*W\n\x08\x46ragInfo\x12\x15\n\x11\x46RAG_CONTINUATION\x10\x00\x12\x0e\n\nFRAG_FIRST\x10\x01\x12\r\n\tFRAG_LAST\x10\x02\x12\x15\n\x11\x46RAG_UNFRAGMENTED\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.FragInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAGINFO._serialized_start=93
  _FRAGINFO._serialized_end=180
# @@protoc_insertion_point(module_scope)
