# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/HeadUnitInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/control/message/HeadUnitInfo.proto\x12$aap_protobuf.service.control.message\"\xc4\x01\n\x0cHeadUnitInfo\x12\x0c\n\x04make\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x12\n\nvehicle_id\x18\x04 \x01(\t\x12\x16\n\x0ehead_unit_make\x18\x05 \x01(\t\x12\x17\n\x0fhead_unit_model\x18\x06 \x01(\t\x12 \n\x18head_unit_software_build\x18\x07 \x01(\t\x12\"\n\x1ahead_unit_software_version\x18\x08 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.HeadUnitInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADUNITINFO._serialized_start=98
  _HEADUNITINFO._serialized_end=294
# @@protoc_insertion_point(module_scope)
