# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/NavFocusType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/control/message/NavFocusType.proto\x12$aap_protobuf.service.control.message*=\n\x0cNavFocusType\x12\x14\n\x10NAV_FOCUS_NATIVE\x10\x01\x12\x17\n\x13NAV_FOCUS_PROJECTED\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.NavFocusType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVFOCUSTYPE._serialized_start=97
  _NAVFOCUSTYPE._serialized_end=158
# @@protoc_insertion_point(module_scope)
