# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/PingConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/control/message/PingConfiguration.proto\x12$aap_protobuf.service.control.message\"{\n\x11PingConfiguration\x12\x12\n\ntimeout_ms\x18\x01 \x01(\r\x12\x13\n\x0binterval_ms\x18\x02 \x01(\r\x12!\n\x19high_latency_threshold_ms\x18\x03 \x01(\r\x12\x1a\n\x12tracked_ping_count\x18\x04 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.PingConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGCONFIGURATION._serialized_start=102
  _PINGCONFIGURATION._serialized_end=225
# @@protoc_insertion_point(module_scope)
