# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ServiceDiscoveryUpdate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service import Service_pb2 as aap__protobuf_dot_service_dot_Service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/control/message/ServiceDiscoveryUpdate.proto\x12$aap_protobuf.service.control.message\x1a\"aap_protobuf/service/Service.proto\"U\n\x16ServiceDiscoveryUpdate\x12;\n\x07service\x18\x01 \x01(\x0b\x32*.aap_protobuf.service.ServiceConfiguration')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ServiceDiscoveryUpdate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICEDISCOVERYUPDATE._serialized_start=143
  _SERVICEDISCOVERYUPDATE._serialized_end=228
# @@protoc_insertion_point(module_scope)
