# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/ServiceDiscoveryResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service import Service_pb2 as aap__protobuf_dot_service_dot_Service__pb2
from aasdk_proto.aap_protobuf.service.control.message import ConnectionConfiguration_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_ConnectionConfiguration__pb2
from aasdk_proto.aap_protobuf.service.control.message import DriverPosition_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_DriverPosition__pb2
from aasdk_proto.aap_protobuf.service.control.message import HeadUnitInfo_pb2 as aap__protobuf_dot_service_dot_control_dot_message_dot_HeadUnitInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/control/message/ServiceDiscoveryResponse.proto\x12$aap_protobuf.service.control.message\x1a\"aap_protobuf/service/Service.proto\x1a\x42\x61\x61p_protobuf/service/control/message/ConnectionConfiguration.proto\x1a\x39\x61\x61p_protobuf/service/control/message/DriverPosition.proto\x1a\x37\x61\x61p_protobuf/service/control/message/HeadUnitInfo.proto\"\xa6\x05\n\x18ServiceDiscoveryResponse\x12<\n\x08\x63hannels\x18\x01 \x03(\x0b\x32*.aap_protobuf.service.ServiceConfiguration\x12\x10\n\x04make\x18\x02 \x01(\tB\x02\x18\x01\x12\x11\n\x05model\x18\x03 \x01(\tB\x02\x18\x01\x12\x10\n\x04year\x18\x04 \x01(\tB\x02\x18\x01\x12\x16\n\nvehicle_id\x18\x05 \x01(\tB\x02\x18\x01\x12M\n\x0f\x64river_position\x18\x06 \x01(\x0e\x32\x34.aap_protobuf.service.control.message.DriverPosition\x12\x1a\n\x0ehead_unit_make\x18\x07 \x01(\tB\x02\x18\x01\x12\x1b\n\x0fhead_unit_model\x18\x08 \x01(\tB\x02\x18\x01\x12$\n\x18head_unit_software_build\x18\t \x01(\tB\x02\x18\x01\x12&\n\x1ahead_unit_software_version\x18\n \x01(\tB\x02\x18\x01\x12+\n\x1f\x63\x61n_play_native_media_during_vr\x18\x0b \x01(\x08\x42\x02\x18\x01\x12\x1d\n\x15session_configuration\x18\r \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x0e \x01(\t\x12\x19\n\x11probe_for_support\x18\x0f \x01(\x08\x12_\n\x18\x63onnection_configuration\x18\x10 \x01(\x0b\x32=.aap_protobuf.service.control.message.ConnectionConfiguration\x12I\n\rheadunit_info\x18\x11 \x01(\x0b\x32\x32.aap_protobuf.service.control.message.HeadUnitInfo')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.ServiceDiscoveryResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['make']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['make']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['model']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['model']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['year']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['year']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['vehicle_id']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['vehicle_id']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_make']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_make']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_model']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_model']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_software_build']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_software_build']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_software_version']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['head_unit_software_version']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE.fields_by_name['can_play_native_media_during_vr']._options = None
  _SERVICEDISCOVERYRESPONSE.fields_by_name['can_play_native_media_during_vr']._serialized_options = b'\030\001'
  _SERVICEDISCOVERYRESPONSE._serialized_start=330
  _SERVICEDISCOVERYRESPONSE._serialized_end=1008
# @@protoc_insertion_point(module_scope)
