# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/UpdateUiConfigRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import UiConfig_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_UiConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@aap_protobuf/service/control/message/UpdateUiConfigRequest.proto\x12$aap_protobuf.service.control.message\x1a\x38\x61\x61p_protobuf/service/media/shared/message/UiConfig.proto\"_\n\x15UpdateUiConfigRequest\x12\x46\n\tui_config\x18\x01 \x01(\x0b\x32\x33.aap_protobuf.service.media.shared.message.UiConfig')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.UpdateUiConfigRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATEUICONFIGREQUEST._serialized_start=164
  _UPDATEUICONFIGREQUEST._serialized_end=259
# @@protoc_insertion_point(module_scope)
