# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/message/WirelessTcpConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCaap_protobuf/service/control/message/WirelessTcpConfiguration.proto\x12$aap_protobuf.service.control.message\"\x85\x01\n\x18WirelessTcpConfiguration\x12%\n\x1dsocket_receive_buffer_size_kb\x18\x01 \x01(\r\x12\"\n\x1asocket_send_buffer_size_kb\x18\x02 \x01(\r\x12\x1e\n\x16socket_read_timeout_ms\x18\x03 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.message.WirelessTcpConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIRELESSTCPCONFIGURATION._serialized_start=110
  _WIRELESSTCPCONFIGURATION._serialized_end=243
# @@protoc_insertion_point(module_scope)
