# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/FeedbackEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/inputsource/message/FeedbackEvent.proto\x12(aap_protobuf.service.inputsource.message*\x89\x01\n\rFeedbackEvent\x12\x13\n\x0f\x46\x45\x45\x44\x42\x41\x43K_SELECT\x10\x01\x12\x19\n\x15\x46\x45\x45\x44\x42\x41\x43K_FOCUS_CHANGE\x10\x02\x12\x18\n\x14\x46\x45\x45\x44\x42\x41\x43K_DRAG_SELECT\x10\x03\x12\x17\n\x13\x46\x45\x45\x44\x42\x41\x43K_DRAG_START\x10\x04\x12\x15\n\x11\x46\x45\x45\x44\x42\x41\x43K_DRAG_END\x10\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.FeedbackEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEEDBACKEVENT._serialized_start=107
  _FEEDBACKEVENT._serialized_end=244
# @@protoc_insertion_point(module_scope)
