# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/InputFeedback.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.inputsource.message import FeedbackEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_FeedbackEvent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/inputsource/message/InputFeedback.proto\x12(aap_protobuf.service.inputsource.message\x1a<aap_protobuf/service/inputsource/message/FeedbackEvent.proto\"W\n\rInputFeedback\x12\x46\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x37.aap_protobuf.service.inputsource.message.FeedbackEvent')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.InputFeedback_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTFEEDBACK._serialized_start=168
  _INPUTFEEDBACK._serialized_end=255
# @@protoc_insertion_point(module_scope)
