# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/RelativeEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aap_protobuf/service/inputsource/message/RelativeEvent.proto\x12(aap_protobuf.service.inputsource.message\"\x81\x01\n\rRelativeEvent\x12I\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32;.aap_protobuf.service.inputsource.message.RelativeEvent.Rel\x1a%\n\x03Rel\x12\x0f\n\x07keycode\x18\x01 \x02(\r\x12\r\n\x05\x64\x65lta\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.RelativeEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RELATIVEEVENT._serialized_start=107
  _RELATIVEEVENT._serialized_end=236
  _RELATIVEEVENT_REL._serialized_start=199
  _RELATIVEEVENT_REL._serialized_end=236
# @@protoc_insertion_point(module_scope)
