# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/message/TouchScreenType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>aap_protobuf/service/inputsource/message/TouchScreenType.proto\x12(aap_protobuf.service.inputsource.message*>\n\x0fTouchScreenType\x12\x0e\n\nCAPACITIVE\x10\x01\x12\r\n\tRESISTIVE\x10\x02\x12\x0c\n\x08INFRARED\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.message.TouchScreenType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOUCHSCREENTYPE._serialized_start=108
  _TOUCHSCREENTYPE._serialized_end=170
# @@protoc_insertion_point(module_scope)
