# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/Insets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6aap_protobuf/service/media/shared/message/Insets.proto\x12)aap_protobuf.service.media.shared.message\"B\n\x06Insets\x12\x0b\n\x03top\x18\x01 \x01(\r\x12\x0e\n\x06\x62ottom\x18\x02 \x01(\r\x12\x0c\n\x04left\x18\x03 \x01(\r\x12\r\n\x05right\x18\x04 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.Insets_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSETS._serialized_start=101
  _INSETS._serialized_end=167
# @@protoc_insertion_point(module_scope)
