# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/Setup.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import MediaCodecType_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_MediaCodecType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aap_protobuf/service/media/shared/message/Setup.proto\x12)aap_protobuf.service.media.shared.message\x1a>aap_protobuf/service/media/shared/message/MediaCodecType.proto\"P\n\x05Setup\x12G\n\x04type\x18\x01 \x02(\x0e\x32\x39.aap_protobuf.service.media.shared.message.MediaCodecType')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.Setup_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUP._serialized_start=164
  _SETUP._serialized_end=244
# @@protoc_insertion_point(module_scope)
