# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/UiConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.media.shared.message import UiTheme_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_UiTheme__pb2
from aasdk_proto.aap_protobuf.service.media.shared.message import Insets_pb2 as aap__protobuf_dot_service_dot_media_dot_shared_dot_message_dot_Insets__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8aap_protobuf/service/media/shared/message/UiConfig.proto\x12)aap_protobuf.service.media.shared.message\x1a\x37\x61\x61p_protobuf/service/media/shared/message/UiTheme.proto\x1a\x36\x61\x61p_protobuf/service/media/shared/message/Insets.proto\"\xb1\x02\n\x08UiConfig\x12\x42\n\x07margins\x18\x01 \x01(\x0b\x32\x31.aap_protobuf.service.media.shared.message.Insets\x12I\n\x0e\x63ontent_insets\x18\x02 \x01(\x0b\x32\x31.aap_protobuf.service.media.shared.message.Insets\x12P\n\x15stable_content_insets\x18\x03 \x01(\x0b\x32\x31.aap_protobuf.service.media.shared.message.Insets\x12\x44\n\x08ui_theme\x18\x04 \x01(\x0e\x32\x32.aap_protobuf.service.media.shared.message.UiTheme')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.UiConfig_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UICONFIG._serialized_start=217
  _UICONFIG._serialized_end=522
# @@protoc_insertion_point(module_scope)
