# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/UiTheme.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7aap_protobuf/service/media/shared/message/UiTheme.proto\x12)aap_protobuf.service.media.shared.message*H\n\x07UiTheme\x12\x16\n\x12UI_THEME_AUTOMATIC\x10\x00\x12\x12\n\x0eUI_THEME_LIGHT\x10\x01\x12\x11\n\rUI_THEME_DARK\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.UiTheme_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UITHEME._serialized_start=102
  _UITHEME._serialized_end=174
# @@protoc_insertion_point(module_scope)
