# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/message/MediaBrowserInput.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.shared import InstrumentClusterInput_pb2 as aap__protobuf_dot_shared_dot_InstrumentClusterInput__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAaap_protobuf/service/mediabrowser/message/MediaBrowserInput.proto\x12)aap_protobuf.service.mediabrowser.message\x1a\x30\x61\x61p_protobuf/shared/InstrumentClusterInput.proto\"]\n\x11MediaBrowserInput\x12:\n\x05input\x18\x01 \x02(\x0b\x32+.aap_protobuf.shared.InstrumentClusterInput\x12\x0c\n\x04path\x18\x02 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaBrowserInput_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIABROWSERINPUT._serialized_start=162
  _MEDIABROWSERINPUT._serialized_end=255
# @@protoc_insertion_point(module_scope)
