# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/mediabrowser/message/MediaRootNode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.mediabrowser.message import MediaSource_pb2 as aap__protobuf_dot_service_dot_mediabrowser_dot_message_dot_MediaSource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=aap_protobuf/service/mediabrowser/message/MediaRootNode.proto\x12)aap_protobuf.service.mediabrowser.message\x1a;aap_protobuf/service/mediabrowser/message/MediaSource.proto\"l\n\rMediaRootNode\x12\x0c\n\x04path\x18\x01 \x02(\t\x12M\n\rmedia_sources\x18\x02 \x03(\x0b\x32\x36.aap_protobuf.service.mediabrowser.message.MediaSource')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.mediabrowser.message.MediaRootNode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEDIAROOTNODE._serialized_start=169
  _MEDIAROOTNODE._serialized_end=277
# @@protoc_insertion_point(module_scope)
