# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/WifiVersionResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*aap_protobuf/aaw/WifiVersionResponse.proto\x12\x10\x61\x61p_protobuf.aaw\"y\n\x13WifiVersionResponse\x12\x17\n\x0funknown_value_a\x18\x01 \x02(\r\x12\x17\n\x0funknown_value_b\x18\x02 \x02(\r\x12\x17\n\x0funknown_value_c\x18\x03 \x01(\t\x12\x17\n\x0funknown_value_d\x18\x04 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.WifiVersionResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIVERSIONRESPONSE._serialized_start=64
  _WIFIVERSIONRESPONSE._serialized_end=185
# @@protoc_insertion_point(module_scope)
