# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/inputsource/InputSourceService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.inputsource.message import FeedbackEvent_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_FeedbackEvent__pb2
from aasdk_proto.aap_protobuf.service.inputsource.message import TouchScreenType_pb2 as aap__protobuf_dot_service_dot_inputsource_dot_message_dot_TouchScreenType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9aap_protobuf/service/inputsource/InputSourceService.proto\x12 aap_protobuf.service.inputsource\x1a<aap_protobuf/service/inputsource/message/FeedbackEvent.proto\x1a>aap_protobuf/service/inputsource/message/TouchScreenType.proto\"\x8f\x05\n\x12InputSourceService\x12\x1e\n\x12keycodes_supported\x18\x01 \x03(\x05\x42\x02\x10\x01\x12U\n\x0btouchscreen\x18\x02 \x03(\x0b\x32@.aap_protobuf.service.inputsource.InputSourceService.TouchScreen\x12O\n\x08touchpad\x18\x03 \x03(\x0b\x32=.aap_protobuf.service.inputsource.InputSourceService.TouchPad\x12Z\n\x19\x66\x65\x65\x64\x62\x61\x63k_events_supported\x18\x04 \x03(\x0e\x32\x37.aap_protobuf.service.inputsource.message.FeedbackEvent\x12\x12\n\ndisplay_id\x18\x05 \x01(\r\x1a\x8b\x01\n\x0bTouchScreen\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12G\n\x04type\x18\x03 \x01(\x0e\x32\x39.aap_protobuf.service.inputsource.message.TouchScreenType\x12\x14\n\x0cis_secondary\x18\x04 \x01(\x08\x1a\xb2\x01\n\x08TouchPad\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\x15\n\rui_navigation\x18\x03 \x01(\x08\x12\x16\n\x0ephysical_width\x18\x04 \x01(\x05\x12\x17\n\x0fphysical_height\x18\x05 \x01(\x05\x12\x13\n\x0bui_absolute\x18\x06 \x01(\x08\x12\x15\n\rtap_as_select\x18\x07 \x01(\x08\x12\x13\n\x0bsensitivity\x18\x08 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.inputsource.InputSourceService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTSOURCESERVICE.fields_by_name['keycodes_supported']._options = None
  _INPUTSOURCESERVICE.fields_by_name['keycodes_supported']._serialized_options = b'\020\001'
  _INPUTSOURCESERVICE._serialized_start=222
  _INPUTSOURCESERVICE._serialized_end=877
  _INPUTSOURCESERVICE_TOUCHSCREEN._serialized_start=557
  _INPUTSOURCESERVICE_TOUCHSCREEN._serialized_end=696
  _INPUTSOURCESERVICE_TOUCHPAD._serialized_start=699
  _INPUTSOURCESERVICE_TOUCHPAD._serialized_end=877
# @@protoc_insertion_point(module_scope)
