# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/AudioConfiguration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBaap_protobuf/service/media/shared/message/AudioConfiguration.proto\x12)aap_protobuf.service.media.shared.message\"_\n\x12\x41udioConfiguration\x12\x15\n\rsampling_rate\x18\x01 \x02(\r\x12\x16\n\x0enumber_of_bits\x18\x02 \x02(\r\x12\x1a\n\x12number_of_channels\x18\x03 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.AudioConfiguration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOCONFIGURATION._serialized_start=113
  _AUDIOCONFIGURATION._serialized_end=208
# @@protoc_insertion_point(module_scope)
