# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/Config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6aap_protobuf/service/media/shared/message/Config.proto\x12)aap_protobuf.service.media.shared.message\"\xb3\x01\n\x06\x43onfig\x12H\n\x06status\x18\x01 \x02(\x0e\x32\x38.aap_protobuf.service.media.shared.message.Config.Status\x12\x13\n\x0bmax_unacked\x18\x02 \x01(\r\x12\x1d\n\x15\x63onfiguration_indices\x18\x03 \x03(\r\"+\n\x06Status\x12\x0f\n\x0bSTATUS_WAIT\x10\x01\x12\x10\n\x0cSTATUS_READY\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.Config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=102
  _CONFIG._serialized_end=281
  _CONFIG_STATUS._serialized_start=238
  _CONFIG_STATUS._serialized_end=281
# @@protoc_insertion_point(module_scope)
