# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/media/shared/message/Start.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aap_protobuf/service/media/shared/message/Start.proto\x12)aap_protobuf.service.media.shared.message\"8\n\x05Start\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\x1b\n\x13\x63onfiguration_index\x18\x02 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.media.shared.message.Start_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _START._serialized_start=100
  _START._serialized_end=156
# @@protoc_insertion_point(module_scope)
