# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/service/control/ControlMessageType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5aap_protobuf/service/control/ControlMessageType.proto\x12$aap_protobuf.service.control.message*\xb1\x07\n\x12\x43ontrolMessageType\x12\x1b\n\x17MESSAGE_VERSION_REQUEST\x10\x01\x12\x1c\n\x18MESSAGE_VERSION_RESPONSE\x10\x02\x12\x1c\n\x18MESSAGE_ENCAPSULATED_SSL\x10\x03\x12\x19\n\x15MESSAGE_AUTH_COMPLETE\x10\x04\x12%\n!MESSAGE_SERVICE_DISCOVERY_REQUEST\x10\x05\x12&\n\"MESSAGE_SERVICE_DISCOVERY_RESPONSE\x10\x06\x12 \n\x1cMESSAGE_CHANNEL_OPEN_REQUEST\x10\x07\x12!\n\x1dMESSAGE_CHANNEL_OPEN_RESPONSE\x10\x08\x12&\n\"MESSAGE_CHANNEL_CLOSE_NOTIFICATION\x10\t\x12\x18\n\x14MESSAGE_PING_REQUEST\x10\x0b\x12\x19\n\x15MESSAGE_PING_RESPONSE\x10\x0c\x12\x1d\n\x19MESSAGE_NAV_FOCUS_REQUEST\x10\r\x12\"\n\x1eMESSAGE_NAV_FOCUS_NOTIFICATION\x10\x0e\x12\x1a\n\x16MESSAGE_BYEBYE_REQUEST\x10\x0f\x12\x1b\n\x17MESSAGE_BYEBYE_RESPONSE\x10\x10\x12&\n\"MESSAGE_VOICE_SESSION_NOTIFICATION\x10\x11\x12\x1f\n\x1bMESSAGE_AUDIO_FOCUS_REQUEST\x10\x12\x12$\n MESSAGE_AUDIO_FOCUS_NOTIFICATION\x10\x13\x12)\n%MESSAGE_CAR_CONNECTED_DEVICES_REQUEST\x10\x14\x12*\n&MESSAGE_CAR_CONNECTED_DEVICES_RESPONSE\x10\x15\x12\x1f\n\x1bMESSAGE_USER_SWITCH_REQUEST\x10\x16\x12\'\n#MESSAGE_BATTERY_STATUS_NOTIFICATION\x10\x17\x12$\n MESSAGE_CALL_AVAILABILITY_STATUS\x10\x18\x12 \n\x1cMESSAGE_USER_SWITCH_RESPONSE\x10\x19\x12$\n MESSAGE_SERVICE_DISCOVERY_UPDATE\x10\x1a\x12\x1f\n\x1aMESSAGE_UNEXPECTED_MESSAGE\x10\xff\x01\x12\x1b\n\x15MESSAGE_FRAMING_ERROR\x10\xff\xff\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.service.control.ControlMessageType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLMESSAGETYPE._serialized_start=96
  _CONTROLMESSAGETYPE._serialized_end=1041
# @@protoc_insertion_point(module_scope)
