# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/MessageId.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n aap_protobuf/aaw/MessageId.proto\x12\x10\x61\x61p_protobuf.aaw*\xbc\x01\n\tMessageId\x12\x16\n\x12WIFI_START_REQUEST\x10\x01\x12\x15\n\x11WIFI_INFO_REQUEST\x10\x02\x12\x16\n\x12WIFI_INFO_RESPONSE\x10\x03\x12\x18\n\x14WIFI_VERSION_REQUEST\x10\x04\x12\x19\n\x15WIFI_VERSION_RESPONSE\x10\x05\x12\x1a\n\x16WIFI_CONNECTION_STATUS\x10\x06\x12\x17\n\x13WIFI_START_RESPONSE\x10\x07')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.MessageId_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEID._serialized_start=55
  _MESSAGEID._serialized_end=243
# @@protoc_insertion_point(module_scope)
