# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/Status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61\x61p_protobuf/aaw/Status.proto\x12\x10\x61\x61p_protobuf.aaw*\xa2\x04\n\x06Status\x12\x1e\n\x1aSTATUS_UNSOLICITED_MESSAGE\x10\x01\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12)\n\x1cSTATUS_NO_COMPATIBLE_VERSION\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12-\n STATUS_WIFI_INACCESSIBLE_CHANNEL\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_WIFI_INCORRECT_CREDENTIALS\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_PROJECTION_ALREADY_STARTED\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n\x14STATUS_WIFI_DISABLED\x10\xfb\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12(\n\x1bSTATUS_WIFI_NOT_YET_STARTED\x10\xfa\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n\x13STATUS_INVALID_HOST\x10\xf9\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12.\n!STATUS_NO_SUPPORTED_WIFI_CHANNELS\x10\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x34\n\'STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE\x10\xf7\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\'\n\x1aSTATUS_PHONE_WIFI_DISABLED\x10\xf6\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12,\n\x1fSTATUS_WIFI_NETWORK_UNAVAILABLE\x10\xf5\xff\xff\xff\xff\xff\xff\xff\xff\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.Status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=52
  _STATUS._serialized_end=598
# @@protoc_insertion_point(module_scope)
