# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/WifiVersionRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)aap_protobuf/aaw/WifiVersionRequest.proto\x12\x10\x61\x61p_protobuf.aaw\"\x14\n\x12WifiVersionRequest')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.WifiVersionRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIVERSIONREQUEST._serialized_start=63
  _WIFIVERSIONREQUEST._serialized_end=83
# @@protoc_insertion_point(module_scope)
