# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/WifiInfoResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aasdk_proto.aap_protobuf.service.wifiprojection.message import AccessPointType_pb2 as aap__protobuf_dot_service_dot_wifiprojection_dot_message_dot_AccessPointType__pb2
from aasdk_proto.aap_protobuf.service.wifiprojection.message import WifiSecurityMode_pb2 as aap__protobuf_dot_service_dot_wifiprojection_dot_message_dot_WifiSecurityMode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'aap_protobuf/aaw/WifiInfoResponse.proto\x12\x10\x61\x61p_protobuf.aaw\x1a\x41\x61\x61p_protobuf/service/wifiprojection/message/AccessPointType.proto\x1a\x42\x61\x61p_protobuf/service/wifiprojection/message/WifiSecurityMode.proto\"\xf0\x01\n\x10WifiInfoResponse\x12\x0c\n\x04ssid\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\r\n\x05\x62ssid\x18\x03 \x02(\t\x12T\n\rsecurity_mode\x18\x04 \x02(\x0e\x32=.aap_protobuf.service.wifiprojection.message.WifiSecurityMode\x12W\n\x11\x61\x63\x63\x65ss_point_type\x18\x05 \x01(\x0e\x32<.aap_protobuf.service.wifiprojection.message.AccessPointType')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.WifiInfoResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFIINFORESPONSE._serialized_start=197
  _WIFIINFORESPONSE._serialized_end=437
# @@protoc_insertion_point(module_scope)
