# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aap_protobuf/aaw/WifiStartRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'aap_protobuf/aaw/WifiStartRequest.proto\x12\x10\x61\x61p_protobuf.aaw\"4\n\x10WifiStartRequest\x12\x12\n\nip_address\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aap_protobuf.aaw.WifiStartRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFISTARTREQUEST._serialized_start=61
  _WIFISTARTREQUEST._serialized_end=113
# @@protoc_insertion_point(module_scope)
